import type { Condition, Lifecycle } from '@kept/shared';

// The report's words, in the two languages it is written in (D201: English or Arabic). The
// Arabic follows the web catalogue's wording (apps/web/src/locales/ar/messages.po) for every term
// the app already uses: conditions, lifecycles, "Unplaced", "Serial number", "Contents". The
// report is rendered by the server, so these live here rather than in Lingui.

export type ReportLocale = 'en' | 'ar';

export type ReportLabels = {
  title: string;
  things: string;
  places: string;
  photos: string;
  totals: string;
  contents: string;
  page: string;
  of: string;
  serial: string;
  subtotal: string;
  bought: string;
  confidential: string;
  empty: string;
};

type Words = ReportLabels & {
  unplaced: string;
  trashed: string;
  allLocations: string;
  /** "{location}" for an account report's cover: which locations it covers. */
  locationsList: (names: string) => string;
  generated: (who: string, when: string) => string;
  moneyPartial: string;
  thingCount: (n: number, formatted: string) => string;
  filterPlaces: string;
  filterTypes: string;
  filterTags: string;
  withEnded: string;
  withTrashed: string;
  condition: Record<Condition, string>;
  lifecycle: Record<Exclude<Lifecycle, 'in_use'>, string>;
};

const EN: Words = {
  title: 'Inventory report',
  things: 'Things',
  places: 'Places',
  photos: 'With photos',
  totals: 'Totals by currency',
  contents: 'Contents',
  page: 'Page',
  of: 'of',
  serial: 'Serial number',
  subtotal: 'Subtotal',
  bought: 'Bought',
  confidential: 'Private: a record of what you own. Keep it as carefully as the things it lists.',
  empty: 'Nothing matches this report.',
  unplaced: 'Unplaced',
  trashed: 'In the trash',
  allLocations: 'All locations',
  locationsList: (names) => `Covers ${names}`,
  generated: (who, when) => `Generated by ${who} · ${when}`,
  moneyPartial: 'Prices appear only for locations where you can see money.',
  thingCount: (n, f) => (n === 1 ? '1 thing' : `${f} things`),
  filterPlaces: 'Places',
  filterTypes: 'Types',
  filterTags: 'Tags',
  withEnded: 'Includes things no longer in use',
  withTrashed: 'Includes things in the trash',
  condition: { new: 'New', good: 'Good', fair: 'Fair', poor: 'Poor', broken: 'Broken' },
  lifecycle: {
    sold: 'Sold',
    given_away: 'Given away',
    lost: 'Lost',
    disposed: 'Disposed of',
    stolen: 'Stolen',
    destroyed: 'Destroyed',
    returned_to_owner: 'Returned to its owner',
  },
};

const arCount = new Intl.PluralRules('ar');

const AR: Words = {
  title: 'تقرير الجرد',
  things: 'الأشياء',
  places: 'الأماكن',
  photos: 'بصور',
  totals: 'الإجمالي حسب العملة',
  contents: 'المحتويات',
  page: 'صفحة',
  of: 'من',
  serial: 'الرقم التسلسلي',
  subtotal: 'الإجمالي الفرعي',
  bought: 'تاريخ الشراء',
  confidential: 'خاص: سجل بما تملكه. احفظه بعناية كما تحفظ ما فيه.',
  empty: 'لا شيء يطابق هذا التقرير.',
  unplaced: 'بلا مكان',
  trashed: 'في المهملات',
  allLocations: 'كل المواقع',
  locationsList: (names) => `يشمل ${names}`,
  generated: (who, when) => `أنشأه ${who} · ${when}`,
  moneyPartial: 'تظهر الأسعار فقط في المواقع التي يمكنك فيها رؤية المال.',
  thingCount: (n, f) => {
    switch (arCount.select(n)) {
      case 'zero':
        return 'لا أشياء';
      case 'one':
        return 'شيء واحد';
      case 'two':
        return 'شيئان';
      case 'few':
        return `${f} أشياء`;
      case 'many':
        return `${f} شيئًا`;
      default:
        return `${f} شيء`;
    }
  },
  filterPlaces: 'الأماكن',
  filterTypes: 'الأنواع',
  filterTags: 'الوسوم',
  withEnded: 'يشمل الأشياء التي لم تعد مستخدمة',
  withTrashed: 'يشمل الأشياء التي في المهملات',
  condition: { new: 'جديد', good: 'جيد', fair: 'مقبول', poor: 'سيئ', broken: 'معطوب' },
  lifecycle: {
    sold: 'بِيع',
    given_away: 'أُهدي',
    lost: 'مفقود',
    disposed: 'تم التخلص منه',
    stolen: 'سُرق',
    destroyed: 'أُتلف',
    returned_to_owner: 'أُعيد إلى مالكه',
  },
};

export function wordsFor(locale: ReportLocale): Words {
  return locale === 'ar' ? AR : EN;
}

/** The labels the template reads (`d.labels`). */
export function templateLabels(locale: ReportLocale): ReportLabels {
  const w = wordsFor(locale);
  return {
    title: w.title,
    things: w.things,
    places: w.places,
    photos: w.photos,
    totals: w.totals,
    contents: w.contents,
    page: w.page,
    of: w.of,
    serial: w.serial,
    subtotal: w.subtotal,
    bought: w.bought,
    confidential: w.confidential,
    empty: w.empty,
  };
}
