-- Generated by drizzle-kit, then edited by hand in one place: audit_events is PARTITION BY
-- RANGE ("at") (§7.13, monthly partitions), which Drizzle can't declare. Its partitions are
-- created in 0005_tenancy_triggers.
CREATE TABLE "audit_event_subjects" (
	"event_id" uuid NOT NULL,
	"event_at" timestamp with time zone NOT NULL,
	"location_id" uuid NOT NULL,
	"thing_id" uuid NOT NULL,
	CONSTRAINT "audit_event_subjects_event_id_event_at_thing_id_pk" PRIMARY KEY("event_id","event_at","thing_id")
);
--> statement-breakpoint
CREATE TABLE "audit_events" (
	"id" uuid DEFAULT uuidv7() NOT NULL,
	"at" timestamp with time zone DEFAULT date_trunc('milliseconds', now()) NOT NULL,
	"location_id" uuid,
	"owner_account_id" uuid,
	"actor_type" text NOT NULL,
	"actor_id" uuid,
	"action" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" uuid,
	"root_thing_id" uuid,
	"diff" jsonb,
	"request_id" text,
	"undo_of" uuid,
	"undoable_until" timestamp with time zone,
	CONSTRAINT "audit_events_id_at_pk" PRIMARY KEY("id","at"),
	CONSTRAINT "audit_events_id_at_location_uq" UNIQUE("id","at","location_id"),
	CONSTRAINT "audit_events_actor_type_chk" CHECK ("actor_type" IN ('user', 'token', 'system', 'import'))
) PARTITION BY RANGE ("at");
--> statement-breakpoint
CREATE TABLE "currencies" (
	"code" char(3) PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"minor_units" integer NOT NULL,
	"symbol" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	CONSTRAINT "currencies_code_chk" CHECK (code ~ '^[A-Z]{3}$'),
	CONSTRAINT "currencies_minor_units_chk" CHECK (minor_units BETWEEN 0 AND 4)
);
--> statement-breakpoint
CREATE TABLE "places" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"location_id" uuid NOT NULL,
	"parent_id" uuid,
	"name" text NOT NULL,
	"kind_key" text DEFAULT 'room' NOT NULL,
	"is_unplaced" boolean DEFAULT false NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"change_seq" bigint,
	CONSTRAINT "places_location_id_uq" UNIQUE("location_id","id"),
	CONSTRAINT "places_unplaced_top_level_chk" CHECK (NOT is_unplaced OR parent_id IS NULL),
	CONSTRAINT "places_not_own_parent_chk" CHECK (parent_id IS NULL OR parent_id <> id)
);
--> statement-breakpoint
CREATE TABLE "idempotency_keys" (
	"user_id" uuid NOT NULL,
	"key" text NOT NULL,
	"request_hash" text NOT NULL,
	"response" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "idempotency_keys_user_id_key_pk" PRIMARY KEY("user_id","key")
);
--> statement-breakpoint
CREATE TABLE "instance_admins" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"granted_by" uuid,
	"granted_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "instance_settings" (
	"key" text PRIMARY KEY NOT NULL,
	"value" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"change_seq" bigint
);
--> statement-breakpoint
CREATE TABLE "invites" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"location_id" uuid NOT NULL,
	"role" text NOT NULL,
	"membership_expires_at" timestamp with time zone,
	"email" text,
	"token_hash" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_by" uuid,
	"accepted_by" uuid,
	"accepted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"change_seq" bigint,
	CONSTRAINT "invites_token_hash_unique" UNIQUE("token_hash"),
	CONSTRAINT "invites_role_chk" CHECK ("role" IN ('admin', 'member', 'viewer'))
);
--> statement-breakpoint
CREATE TABLE "location_modules" (
	"location_id" uuid NOT NULL,
	"module" text NOT NULL,
	"enabled" boolean NOT NULL,
	"enabled_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"change_seq" bigint,
	CONSTRAINT "location_modules_location_id_module_pk" PRIMARY KEY("location_id","module"),
	CONSTRAINT "location_modules_module_chk" CHECK (module ~ '^[a-z][a-z0-9_]*$')
);
--> statement-breakpoint
CREATE TABLE "locations" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"owner_account_id" uuid NOT NULL,
	"kind" text NOT NULL,
	"name" text NOT NULL,
	"timezone" text NOT NULL,
	"currency" char(3) NOT NULL,
	"languages" text[] DEFAULT '{}'::text[] NOT NULL,
	"address" jsonb,
	"latitude" double precision,
	"longitude" double precision,
	"suggest_radius_m" integer DEFAULT 150 NOT NULL,
	"preset" text DEFAULT 'household' NOT NULL,
	"money_visible_to_viewers" boolean DEFAULT false NOT NULL,
	"require_2fa" boolean DEFAULT false NOT NULL,
	"long_unseen_months" integer DEFAULT 12 NOT NULL,
	"successor_user_id" uuid,
	"deleted_at" timestamp with time zone,
	"purge_after" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"change_seq" bigint,
	CONSTRAINT "locations_id_owner_account_uq" UNIQUE("id","owner_account_id"),
	CONSTRAINT "locations_kind_chk" CHECK ("kind" IN ('personal', 'home', 'apartment', 'garage', 'storage_unit', 'office', 'vacation_home', 'custom')),
	CONSTRAINT "locations_preset_chk" CHECK ("preset" IN ('essentials', 'household', 'complete')),
	CONSTRAINT "locations_latitude_chk" CHECK (latitude BETWEEN -90 AND 90),
	CONSTRAINT "locations_longitude_chk" CHECK (longitude BETWEEN -180 AND 180),
	CONSTRAINT "locations_suggest_radius_chk" CHECK (suggest_radius_m > 0),
	CONSTRAINT "locations_long_unseen_chk" CHECK (long_unseen_months > 0),
	CONSTRAINT "locations_purge_needs_delete_chk" CHECK (purge_after IS NULL OR deleted_at IS NOT NULL)
);
--> statement-breakpoint
CREATE TABLE "memberships" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"location_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"role" text NOT NULL,
	"expires_at" timestamp with time zone,
	"invited_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"change_seq" bigint,
	CONSTRAINT "memberships_location_user_uq" UNIQUE("location_id","user_id"),
	CONSTRAINT "memberships_role_chk" CHECK ("role" IN ('owner', 'admin', 'member', 'viewer')),
	CONSTRAINT "memberships_owner_no_expiry_chk" CHECK (role <> 'owner' OR expires_at IS NULL)
);
--> statement-breakpoint
CREATE TABLE "owner_accounts" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "owner_accounts_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "sync_tombstones" (
	"location_id" uuid NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"change_seq" bigint,
	CONSTRAINT "sync_tombstones_location_id_entity_type_entity_id_pk" PRIMARY KEY("location_id","entity_type","entity_id")
);
--> statement-breakpoint
CREATE TABLE "user_hidden_modules" (
	"user_id" uuid NOT NULL,
	"location_id" uuid NOT NULL,
	"module" text NOT NULL,
	CONSTRAINT "user_hidden_modules_user_id_location_id_module_pk" PRIMARY KEY("user_id","location_id","module"),
	CONSTRAINT "user_hidden_modules_module_chk" CHECK (module ~ '^[a-z][a-z0-9_]*$')
);
--> statement-breakpoint
CREATE TABLE "user_profiles" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"display_name" text NOT NULL,
	"timezone" text DEFAULT 'UTC' NOT NULL,
	"locale" text DEFAULT 'en' NOT NULL,
	"units" text DEFAULT 'metric' NOT NULL,
	"theme" text DEFAULT 'system' NOT NULL,
	"digits" text DEFAULT 'western' NOT NULL,
	"suggest_location" boolean DEFAULT false NOT NULL,
	"digest_time" time,
	"quiet_from" time,
	"quiet_to" time,
	"managed" boolean DEFAULT false NOT NULL,
	"created_by_user_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"change_seq" bigint,
	CONSTRAINT "user_profiles_units_chk" CHECK ("units" IN ('metric', 'imperial')),
	CONSTRAINT "user_profiles_theme_chk" CHECK ("theme" IN ('system', 'light', 'dark')),
	CONSTRAINT "user_profiles_digits_chk" CHECK ("digits" IN ('western', 'eastern'))
);
--> statement-breakpoint
ALTER TABLE "audit_event_subjects" ADD CONSTRAINT "audit_event_subjects_event_fk" FOREIGN KEY ("event_id","event_at","location_id") REFERENCES "public"."audit_events"("id","at","location_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "places" ADD CONSTRAINT "places_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "places" ADD CONSTRAINT "places_parent_fk" FOREIGN KEY ("location_id","parent_id") REFERENCES "public"."places"("location_id","id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "idempotency_keys" ADD CONSTRAINT "idempotency_keys_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "instance_admins" ADD CONSTRAINT "instance_admins_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "instance_admins" ADD CONSTRAINT "instance_admins_granted_by_user_id_fk" FOREIGN KEY ("granted_by") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invites" ADD CONSTRAINT "invites_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invites" ADD CONSTRAINT "invites_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invites" ADD CONSTRAINT "invites_accepted_by_user_id_fk" FOREIGN KEY ("accepted_by") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "location_modules" ADD CONSTRAINT "location_modules_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "locations" ADD CONSTRAINT "locations_owner_account_id_owner_accounts_id_fk" FOREIGN KEY ("owner_account_id") REFERENCES "public"."owner_accounts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "locations" ADD CONSTRAINT "locations_currency_currencies_code_fk" FOREIGN KEY ("currency") REFERENCES "public"."currencies"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "locations" ADD CONSTRAINT "locations_successor_user_id_user_id_fk" FOREIGN KEY ("successor_user_id") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_invited_by_user_id_fk" FOREIGN KEY ("invited_by") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "owner_accounts" ADD CONSTRAINT "owner_accounts_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sync_tombstones" ADD CONSTRAINT "sync_tombstones_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_hidden_modules" ADD CONSTRAINT "user_hidden_modules_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_hidden_modules" ADD CONSTRAINT "user_hidden_modules_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_profiles" ADD CONSTRAINT "user_profiles_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_profiles" ADD CONSTRAINT "user_profiles_created_by_user_id_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "auth"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_event_subjects_thing_idx" ON "audit_event_subjects" USING btree ("thing_id");--> statement-breakpoint
CREATE INDEX "audit_events_entity_idx" ON "audit_events" USING btree ("location_id","entity_type","entity_id","at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "audit_events_location_at_idx" ON "audit_events" USING btree ("location_id","at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "audit_events_actor_idx" ON "audit_events" USING btree ("actor_type","actor_id","at");--> statement-breakpoint
CREATE UNIQUE INDEX "places_one_unplaced_uq" ON "places" USING btree ("location_id") WHERE is_unplaced;--> statement-breakpoint
CREATE INDEX "places_parent_idx" ON "places" USING btree ("location_id","parent_id");--> statement-breakpoint
CREATE INDEX "invites_location_idx" ON "invites" USING btree ("location_id");--> statement-breakpoint
CREATE UNIQUE INDEX "locations_one_personal_uq" ON "locations" USING btree ("owner_account_id") WHERE kind = 'personal';--> statement-breakpoint
CREATE INDEX "locations_owner_account_idx" ON "locations" USING btree ("owner_account_id");--> statement-breakpoint
CREATE UNIQUE INDEX "memberships_one_owner_uq" ON "memberships" USING btree ("location_id") WHERE role = 'owner';--> statement-breakpoint
CREATE INDEX "memberships_user_idx" ON "memberships" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "sync_tombstones_change_seq_idx" ON "sync_tombstones" USING btree ("location_id","change_seq");