-- Generated by drizzle-kit, then edited by hand in one place: attachments_location_id_uq is added
-- before the foreign keys that reference it (drizzle-kit put it after extractions_attachment_fk).
CREATE TABLE "extractions" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"location_id" uuid NOT NULL,
	"attachment_id" uuid NOT NULL,
	"thing_id" uuid,
	"purchase_id" uuid,
	"meter_id" uuid,
	"mode" text NOT NULL,
	"attempt" integer DEFAULT 1 NOT NULL,
	"status" text DEFAULT 'queued' NOT NULL,
	"status_reason" text,
	"paused_until" timestamp with time zone,
	"llm_call_id" uuid,
	"result" jsonb,
	"applied" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"requested_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"change_seq" bigint,
	CONSTRAINT "extractions_location_id_uq" UNIQUE("location_id","id"),
	CONSTRAINT "extractions_attempt_uq" UNIQUE("attachment_id","attempt"),
	CONSTRAINT "extractions_mode_chk" CHECK ("mode" IN ('thing', 'receipt', 'label', 'reading')),
	CONSTRAINT "extractions_status_chk" CHECK ("status" IN ('queued', 'running', 'succeeded', 'failed', 'paused_budget', 'waiting_provider', 'no_provider', 'superseded')),
	CONSTRAINT "extractions_attempt_chk" CHECK (attempt BETWEEN 1 AND 50),
	CONSTRAINT "extractions_status_reason_chk" CHECK (char_length(status_reason) <= 60),
	CONSTRAINT "extractions_one_draft_chk" CHECK (num_nonnulls(thing_id, purchase_id, meter_id) <= 1),
	CONSTRAINT "extractions_result_chk" CHECK (result IS NULL OR jsonb_typeof(result) = 'object'),
	CONSTRAINT "extractions_applied_chk" CHECK (jsonb_typeof(applied) = 'object')
);
--> statement-breakpoint
CREATE TABLE "file_text" (
	"file_id" uuid PRIMARY KEY NOT NULL,
	"location_id" uuid NOT NULL,
	"source" text NOT NULL,
	"text" text NOT NULL,
	"tsv" "tsvector" GENERATED ALWAYS AS (to_tsvector('simple', kept.search_text(left(text, 100000)))) STORED,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "file_text_source_chk" CHECK ("source" IN ('pdf', 'extraction')),
	CONSTRAINT "file_text_text_chk" CHECK (char_length(text) <= 200000)
);
--> statement-breakpoint
CREATE TABLE "inbox_items" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"location_id" uuid NOT NULL,
	"kind" text NOT NULL,
	"thing_id" uuid,
	"purchase_id" uuid,
	"meter_reading_id" uuid,
	"extraction_id" uuid,
	"other_thing_id" uuid,
	"code" char(6),
	"batch_id" uuid,
	"created_by" uuid NOT NULL,
	"payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"resolved_at" timestamp with time zone,
	"resolved_by" uuid,
	"resolution" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"change_seq" bigint,
	CONSTRAINT "inbox_items_location_id_uq" UNIQUE("location_id","id"),
	CONSTRAINT "inbox_items_kind_chk" CHECK ("kind" IN ('draft', 'reading', 'label_claim', 'currency', 'duplicate', 'receipt', 'sync_drop')),
	CONSTRAINT "inbox_items_resolution_chk" CHECK ("resolution" IN ('accepted', 'edited', 'discarded', 'merged', 'linked', 'restored', 'dismissed')),
	CONSTRAINT "inbox_items_code_chk" CHECK (code ~ '^[0-9A-HJKMNP-TV-Z]{6}$'),
	CONSTRAINT "inbox_items_payload_chk" CHECK (jsonb_typeof(payload) = 'object'),
	CONSTRAINT "inbox_items_resolved_chk" CHECK ((resolved_at IS NULL) = (resolution IS NULL)),
	CONSTRAINT "inbox_items_subject_chk" CHECK (kind = 'sync_drop' OR num_nonnulls(thing_id, purchase_id, meter_reading_id, code) >= 1)
);
--> statement-breakpoint
CREATE TABLE "template_locations" (
	"template_id" uuid NOT NULL,
	"owner_account_id" uuid NOT NULL,
	"location_id" uuid NOT NULL,
	CONSTRAINT "template_locations_pk" PRIMARY KEY("template_id","location_id")
);
--> statement-breakpoint
CREATE TABLE "templates" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"owner_account_id" uuid NOT NULL,
	"name" text NOT NULL,
	"type_id" uuid,
	"payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by" uuid NOT NULL,
	"archived_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"change_seq" bigint,
	CONSTRAINT "templates_owner_account_id_uq" UNIQUE("owner_account_id","id"),
	CONSTRAINT "templates_name_chk" CHECK (char_length(name) BETWEEN 1 AND 80),
	CONSTRAINT "templates_payload_chk" CHECK (jsonb_typeof(payload) = 'object')
);
--> statement-breakpoint
CREATE TABLE "import_runs" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"location_id" uuid NOT NULL,
	"source" text NOT NULL,
	"source_version" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"mapping" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"choices" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"rows" jsonb,
	"dry_run_report" jsonb,
	"progress" integer DEFAULT 0 NOT NULL,
	"total" integer,
	"created_by" uuid NOT NULL,
	"started_at" timestamp with time zone,
	"finished_at" timestamp with time zone,
	"error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"change_seq" bigint,
	CONSTRAINT "import_runs_location_id_uq" UNIQUE("location_id","id"),
	CONSTRAINT "import_runs_source_chk" CHECK ("source" IN ('csv', 'homebox_zip', 'homebox_api', 'kept_zip', 'lubelogger_csv')),
	CONSTRAINT "import_runs_status_chk" CHECK ("status" IN ('draft', 'checked', 'running', 'done', 'failed', 'cancelled')),
	CONSTRAINT "import_runs_source_version_chk" CHECK (char_length(source_version) <= 40),
	CONSTRAINT "import_runs_mapping_chk" CHECK (jsonb_typeof(mapping) = 'object'),
	CONSTRAINT "import_runs_choices_chk" CHECK (jsonb_typeof(choices) = 'object'),
	CONSTRAINT "import_runs_rows_chk" CHECK (rows IS NULL OR jsonb_typeof(rows) = 'array'),
	CONSTRAINT "import_runs_progress_chk" CHECK (progress >= 0 AND (total IS NULL OR progress <= total)),
	CONSTRAINT "import_runs_error_chk" CHECK (char_length(error) <= 500)
);
--> statement-breakpoint
CREATE TABLE "import_source_ids" (
	"location_id" uuid NOT NULL,
	"source" text NOT NULL,
	"source_id" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" uuid NOT NULL,
	"run_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "import_source_ids_pk" PRIMARY KEY("location_id","source","source_id"),
	CONSTRAINT "import_source_ids_source_chk" CHECK ("source" IN ('csv', 'homebox_zip', 'homebox_api', 'kept_zip', 'lubelogger_csv')),
	CONSTRAINT "import_source_ids_entity_type_chk" CHECK ("entity_type" IN ('thing', 'place', 'purchase')),
	CONSTRAINT "import_source_ids_source_id_chk" CHECK (char_length(source_id) BETWEEN 1 AND 200)
);
--> statement-breakpoint
ALTER TABLE "purchases" ALTER COLUMN "purchased_on" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "attachments" ADD CONSTRAINT "attachments_location_id_uq" UNIQUE("location_id","id");--> statement-breakpoint
ALTER TABLE "extractions" ADD CONSTRAINT "extractions_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "extractions" ADD CONSTRAINT "extractions_attachment_fk" FOREIGN KEY ("location_id","attachment_id") REFERENCES "public"."attachments"("location_id","id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "extractions" ADD CONSTRAINT "extractions_thing_fk" FOREIGN KEY ("location_id","thing_id") REFERENCES "public"."things"("location_id","id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "extractions" ADD CONSTRAINT "extractions_purchase_fk" FOREIGN KEY ("location_id","purchase_id") REFERENCES "public"."purchases"("location_id","id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "extractions" ADD CONSTRAINT "extractions_meter_fk" FOREIGN KEY ("location_id","meter_id") REFERENCES "public"."meters"("location_id","id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "file_text" ADD CONSTRAINT "file_text_file_fk" FOREIGN KEY ("location_id","file_id") REFERENCES "public"."files"("location_id","id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "inbox_items" ADD CONSTRAINT "inbox_items_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inbox_items" ADD CONSTRAINT "inbox_items_thing_fk" FOREIGN KEY ("location_id","thing_id") REFERENCES "public"."things"("location_id","id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "inbox_items" ADD CONSTRAINT "inbox_items_purchase_fk" FOREIGN KEY ("location_id","purchase_id") REFERENCES "public"."purchases"("location_id","id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "inbox_items" ADD CONSTRAINT "inbox_items_meter_reading_fk" FOREIGN KEY ("location_id","meter_reading_id") REFERENCES "public"."meter_readings"("location_id","id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "inbox_items" ADD CONSTRAINT "inbox_items_extraction_fk" FOREIGN KEY ("location_id","extraction_id") REFERENCES "public"."extractions"("location_id","id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "inbox_items" ADD CONSTRAINT "inbox_items_other_thing_fk" FOREIGN KEY ("location_id","other_thing_id") REFERENCES "public"."things"("location_id","id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "template_locations" ADD CONSTRAINT "template_locations_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "template_locations" ADD CONSTRAINT "template_locations_template_fk" FOREIGN KEY ("owner_account_id","template_id") REFERENCES "public"."templates"("owner_account_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "templates" ADD CONSTRAINT "templates_owner_account_id_owner_accounts_id_fk" FOREIGN KEY ("owner_account_id") REFERENCES "public"."owner_accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "templates" ADD CONSTRAINT "templates_type_id_types_id_fk" FOREIGN KEY ("type_id") REFERENCES "public"."types"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_runs" ADD CONSTRAINT "import_runs_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_source_ids" ADD CONSTRAINT "import_source_ids_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_source_ids" ADD CONSTRAINT "import_source_ids_run_fk" FOREIGN KEY ("location_id","run_id") REFERENCES "public"."import_runs"("location_id","id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE UNIQUE INDEX "extractions_live_uq" ON "extractions" USING btree ("attachment_id") WHERE status IN ('queued', 'running', 'paused_budget', 'waiting_provider');--> statement-breakpoint
CREATE INDEX "extractions_thing_idx" ON "extractions" USING btree ("thing_id") WHERE thing_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX "extractions_purchase_idx" ON "extractions" USING btree ("purchase_id") WHERE purchase_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX "extractions_paused_idx" ON "extractions" USING btree ("location_id","created_at") WHERE status = 'paused_budget';--> statement-breakpoint
CREATE INDEX "file_text_tsv_idx" ON "file_text" USING gin ("tsv");--> statement-breakpoint
CREATE INDEX "file_text_location_idx" ON "file_text" USING btree ("location_id");--> statement-breakpoint
CREATE UNIQUE INDEX "inbox_open_subject_uq" ON "inbox_items" USING btree ("kind",coalesce(thing_id, purchase_id, meter_reading_id),coalesce(other_thing_id, '00000000-0000-0000-0000-000000000000'::uuid),coalesce(code, '')) WHERE resolved_at IS NULL;--> statement-breakpoint
CREATE INDEX "inbox_open_loc_idx" ON "inbox_items" USING btree ("location_id","created_at" DESC NULLS LAST,"id") WHERE resolved_at IS NULL;--> statement-breakpoint
CREATE INDEX "inbox_open_mine_idx" ON "inbox_items" USING btree ("created_by","created_at" DESC NULLS LAST,"id") WHERE resolved_at IS NULL;--> statement-breakpoint
CREATE INDEX "inbox_resolved_idx" ON "inbox_items" USING btree ("resolved_at") WHERE resolved_at IS NOT NULL;--> statement-breakpoint
CREATE INDEX "inbox_items_thing_idx" ON "inbox_items" USING btree ("thing_id") WHERE thing_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX "template_locations_location_idx" ON "template_locations" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "templates_type_idx" ON "templates" USING btree ("type_id");--> statement-breakpoint
CREATE INDEX "import_runs_location_idx" ON "import_runs" USING btree ("location_id","created_at");--> statement-breakpoint
CREATE INDEX "import_source_ids_run_idx" ON "import_source_ids" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX "import_source_ids_entity_idx" ON "import_source_ids" USING btree ("entity_id");--> statement-breakpoint
ALTER TABLE "purchases" ADD CONSTRAINT "purchases_dated_chk" CHECK (purchased_on IS NOT NULL OR review_state = 'draft');