-- Generated by drizzle-kit, then edited by hand in one place: llm_calls is PARTITION BY RANGE ("at")
-- (§7.13, monthly partitions, as audit_events in 0003), which Drizzle can't declare. Its
-- partitions are made in 0040 by kept.ensure_llm_partitions().
CREATE TABLE "ai_breakers" (
	"provider_id" uuid PRIMARY KEY NOT NULL,
	"reason" text,
	"until" timestamp with time zone,
	"trips" integer DEFAULT 0 NOT NULL,
	"recent_errors" timestamp with time zone[] DEFAULT '{}'::timestamptz[] NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ai_breakers_reason_chk" CHECK ("reason" IN ('rate_limited', 'quota', 'auth', 'provider_down')),
	CONSTRAINT "ai_breakers_trip_pair_chk" CHECK ((reason IS NULL) = (until IS NULL)),
	CONSTRAINT "ai_breakers_trips_chk" CHECK (trips >= 0)
);
--> statement-breakpoint
CREATE TABLE "ai_budgets" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"scope" text NOT NULL,
	"owner_account_id" uuid,
	"location_id" uuid,
	"user_id" uuid,
	"task" text,
	"tokens_per_minute" integer,
	"tokens_per_day" integer,
	"tokens_per_month" bigint,
	"monthly_cap_amount" numeric(16, 4),
	"cap_currency" char(3),
	"paused_until" timestamp with time zone,
	"paused_reason" text,
	"warned_80_month" date,
	"warned_100_month" date,
	"set_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"change_seq" bigint,
	CONSTRAINT "ai_budgets_scope_uq" UNIQUE NULLS NOT DISTINCT("scope","owner_account_id","location_id","user_id","task"),
	CONSTRAINT "ai_budgets_scope_chk" CHECK ("scope" IN ('instance', 'instance_account', 'account', 'location', 'member', 'user')),
	CONSTRAINT "ai_budgets_task_chk" CHECK ("task" IN ('extraction', 'assistant', 'embeddings')),
	CONSTRAINT "ai_budgets_paused_reason_chk" CHECK ("paused_reason" IN ('manual', 'cap_money', 'cap_tokens', 'tokens_day')),
	CONSTRAINT "ai_budgets_tpm_chk" CHECK (tokens_per_minute > 0),
	CONSTRAINT "ai_budgets_tpd_chk" CHECK (tokens_per_day > 0),
	CONSTRAINT "ai_budgets_month_tokens_chk" CHECK (tokens_per_month > 0),
	CONSTRAINT "ai_budgets_money_chk" CHECK (monthly_cap_amount >= 0),
	CONSTRAINT "ai_budgets_money_pair_chk" CHECK ((monthly_cap_amount IS NULL) = (cap_currency IS NULL)),
	CONSTRAINT "ai_budgets_pause_pair_chk" CHECK ((paused_until IS NULL) = (paused_reason IS NULL)),
	CONSTRAINT "ai_budgets_scope_ids_chk" CHECK (CASE scope
            WHEN 'instance' THEN owner_account_id IS NULL AND location_id IS NULL AND user_id IS NULL
            WHEN 'instance_account' THEN location_id IS NULL AND user_id IS NULL
            WHEN 'account' THEN owner_account_id IS NOT NULL AND location_id IS NULL AND user_id IS NULL
            WHEN 'location' THEN owner_account_id IS NOT NULL AND location_id IS NOT NULL AND user_id IS NULL
            WHEN 'member' THEN owner_account_id IS NOT NULL AND location_id IS NULL AND user_id IS NOT NULL
            ELSE owner_account_id IS NULL AND location_id IS NULL AND user_id IS NOT NULL END),
	CONSTRAINT "ai_budgets_minute_day_chk" CHECK ((tokens_per_minute IS NULL AND tokens_per_day IS NULL)
          OR (scope IN ('instance', 'account') AND task IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "ai_cost_windows" (
	"bucket" text NOT NULL,
	"month_start" date NOT NULL,
	"currency" char(3) NOT NULL,
	"amount" numeric(16, 6) DEFAULT '0' NOT NULL,
	CONSTRAINT "ai_cost_windows_pk" PRIMARY KEY("bucket","month_start","currency")
);
--> statement-breakpoint
CREATE TABLE "ai_leases" (
	"lease_key" text NOT NULL,
	"slot" smallint NOT NULL,
	"job_id" text NOT NULL,
	"lease_until" timestamp with time zone NOT NULL,
	CONSTRAINT "ai_leases_pk" PRIMARY KEY("lease_key","slot"),
	CONSTRAINT "ai_leases_slot_chk" CHECK (slot BETWEEN 1 AND 4)
);
--> statement-breakpoint
CREATE TABLE "ai_model_prices" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"provider_kind" text NOT NULL,
	"model" text NOT NULL,
	"version" integer NOT NULL,
	"input_per_mtok" numeric(16, 6) NOT NULL,
	"output_per_mtok" numeric(16, 6) NOT NULL,
	"reasoning_per_mtok" numeric(16, 6),
	"cached_input_per_mtok" numeric(16, 6),
	"per_image" numeric(16, 6),
	"currency" char(3) NOT NULL,
	"effective_from" timestamp with time zone DEFAULT now() NOT NULL,
	"superseded_at" timestamp with time zone,
	"source" text NOT NULL,
	"listing_fetched_at" timestamp with time zone,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ai_model_prices_version_uq" UNIQUE("provider_kind","model","version"),
	CONSTRAINT "ai_model_prices_source_chk" CHECK ("source" IN ('admin', 'provider_listing')),
	CONSTRAINT "ai_model_prices_kind_chk" CHECK (provider_kind IN ('openai', 'anthropic', 'google', 'openai_compatible', 'openrouter', 'groq')),
	CONSTRAINT "ai_model_prices_model_chk" CHECK (char_length(model) BETWEEN 1 AND 120),
	CONSTRAINT "ai_model_prices_version_chk" CHECK (version >= 1),
	CONSTRAINT "ai_model_prices_rates_chk" CHECK (input_per_mtok >= 0 AND output_per_mtok >= 0 AND reasoning_per_mtok >= 0
          AND cached_input_per_mtok >= 0 AND per_image >= 0),
	CONSTRAINT "ai_model_prices_listing_chk" CHECK (source = 'admin' OR listing_fetched_at IS NOT NULL),
	CONSTRAINT "ai_model_prices_superseded_chk" CHECK (superseded_at IS NULL OR superseded_at >= effective_from)
);
--> statement-breakpoint
CREATE TABLE "ai_provider_limits" (
	"provider_id" uuid PRIMARY KEY NOT NULL,
	"limit_tokens" integer,
	"remaining_tokens" integer,
	"reset_at" timestamp with time zone,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ai_providers" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"scope" text NOT NULL,
	"owner_account_id" uuid,
	"user_id" uuid,
	"kind" text NOT NULL,
	"model_list" jsonb,
	"model_list_at" timestamp with time zone,
	"label" text,
	"base_url" text,
	"key_ciphertext" jsonb,
	"key_version" integer,
	"key_hint" text,
	"models" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"capabilities" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"reasoning" text DEFAULT 'low' NOT NULL,
	"disabled_at" timestamp with time zone,
	"created_by" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"change_seq" bigint,
	CONSTRAINT "ai_providers_scope_chk" CHECK ("scope" IN ('instance', 'account', 'user')),
	CONSTRAINT "ai_providers_kind_chk" CHECK ("kind" IN ('openai', 'anthropic', 'google', 'openai_compatible', 'openrouter', 'groq')),
	CONSTRAINT "ai_providers_reasoning_chk" CHECK (reasoning IN ('provider-default', 'none', 'minimal', 'low', 'medium', 'high')),
	CONSTRAINT "ai_providers_label_chk" CHECK (char_length(label) <= 60),
	CONSTRAINT "ai_providers_base_url_chk" CHECK (base_url IS NULL OR (base_url ~ '^https?://' AND char_length(base_url) <= 300)),
	CONSTRAINT "ai_providers_key_hint_chk" CHECK (key_hint ~ '^[A-Za-z0-9_-]{0,4}$'),
	CONSTRAINT "ai_providers_models_chk" CHECK (jsonb_typeof(models) = 'object'),
	CONSTRAINT "ai_providers_capabilities_chk" CHECK (jsonb_typeof(capabilities) = 'object'),
	CONSTRAINT "ai_providers_scope_ids_chk" CHECK (CASE scope WHEN 'instance' THEN owner_account_id IS NULL AND user_id IS NULL
                     WHEN 'account' THEN owner_account_id IS NOT NULL AND user_id IS NULL
                     ELSE user_id IS NOT NULL AND owner_account_id IS NULL END),
	CONSTRAINT "ai_providers_key_pair_chk" CHECK ((key_ciphertext IS NULL) = (key_version IS NULL)),
	CONSTRAINT "ai_providers_compatible_chk" CHECK (kind <> 'openai_compatible' OR base_url IS NOT NULL),
	CONSTRAINT "ai_providers_keyed_chk" CHECK (kind = 'openai_compatible' OR key_ciphertext IS NOT NULL OR disabled_at IS NOT NULL)
);
--> statement-breakpoint
CREATE TABLE "ai_usage_months" (
	"month" date NOT NULL,
	"paying_scope" text NOT NULL,
	"paying_account_id" uuid,
	"paying_user_id" uuid,
	"location_id" uuid,
	"owner_account_id" uuid,
	"user_id" uuid,
	"task" text NOT NULL,
	"provider_kind" text NOT NULL,
	"model" text NOT NULL,
	"cost_currency" char(3),
	"calls" integer NOT NULL,
	"sent_calls" integer NOT NULL,
	"tokens" bigint NOT NULL,
	"input_tokens" bigint DEFAULT 0 NOT NULL,
	"output_tokens" bigint DEFAULT 0 NOT NULL,
	"reasoning_tokens" bigint DEFAULT 0 NOT NULL,
	"cached_tokens" bigint DEFAULT 0 NOT NULL,
	"images" integer NOT NULL,
	"cost_amount" numeric(18, 6),
	"unknown_cost_calls" integer NOT NULL,
	"outcomes" jsonb DEFAULT '{}'::jsonb NOT NULL,
	CONSTRAINT "ai_usage_months_uq" UNIQUE NULLS NOT DISTINCT("month","paying_scope","paying_account_id","paying_user_id","location_id","user_id","task","provider_kind","model","cost_currency"),
	CONSTRAINT "ai_usage_months_paying_scope_chk" CHECK ("paying_scope" IN ('instance', 'account', 'user'))
);
--> statement-breakpoint
CREATE TABLE "ai_usage_windows" (
	"bucket" text NOT NULL,
	"window_kind" text NOT NULL,
	"window_start" timestamp with time zone NOT NULL,
	"tokens" bigint DEFAULT 0 NOT NULL,
	"calls" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "ai_usage_windows_pk" PRIMARY KEY("bucket","window_kind","window_start"),
	CONSTRAINT "ai_usage_windows_window_kind_chk" CHECK ("window_kind" IN ('minute', 'day', 'month'))
);
--> statement-breakpoint
CREATE TABLE "llm_calls" (
	"id" uuid DEFAULT uuidv7() NOT NULL,
	"at" timestamp with time zone DEFAULT date_trunc('milliseconds', now()) NOT NULL,
	"request_id" text NOT NULL,
	"attempt" smallint DEFAULT 1 NOT NULL,
	"task" text NOT NULL,
	"budget_task" text GENERATED ALWAYS AS (CASE WHEN task LIKE 'extract\_%' THEN 'extraction'
               WHEN task LIKE 'assistant\_%' THEN 'assistant'
               WHEN task LIKE 'embed\_%' THEN 'embeddings' ELSE 'test' END) STORED,
	"location_id" uuid,
	"owner_account_id" uuid,
	"user_id" uuid,
	"paying_scope" text NOT NULL,
	"paying_account_id" uuid,
	"paying_user_id" uuid,
	"fell_back" boolean DEFAULT false NOT NULL,
	"provider_id" uuid,
	"provider_kind" text NOT NULL,
	"model" text NOT NULL,
	"reasoning" text,
	"prompt_version" text,
	"sent" boolean NOT NULL,
	"estimate_tokens" integer,
	"input_tokens" integer,
	"output_tokens" integer,
	"reasoning_tokens" integer,
	"cached_input_tokens" integer,
	"image_count" smallint DEFAULT 0 NOT NULL,
	"image_tokens_each" integer,
	"image_bytes" integer,
	"attachment_ids" uuid[],
	"latency_ms" integer,
	"finish_reason" text,
	"outcome" text NOT NULL,
	"error_code" text,
	"http_status" smallint,
	"cost_amount" numeric(16, 6),
	"cost_currency" char(3),
	"cost_source" text NOT NULL,
	"price_id" uuid,
	"extraction_id" uuid,
	"thread_id" uuid,
	"thing_id" uuid,
	"rl_remaining_tokens" integer,
	"rl_reset_at" timestamp with time zone,
	CONSTRAINT "llm_calls_pk" PRIMARY KEY("id","at"),
	CONSTRAINT "llm_calls_task_chk" CHECK ("task" IN ('extract_thing', 'extract_receipt', 'extract_label', 'extract_reading', 'assistant_turn', 'assistant_followup', 'embed_thing', 'embed_query', 'connection_test')),
	CONSTRAINT "llm_calls_outcome_chk" CHECK ("outcome" IN ('ok', 'refused', 'rate_limited', 'over_budget', 'provider_error', 'timeout', 'schema_invalid', 'truncated')),
	CONSTRAINT "llm_calls_cost_source_chk" CHECK ("cost_source" IN ('provider', 'price_table', 'price_table_later', 'unknown', 'not_sent')),
	CONSTRAINT "llm_calls_paying_scope_chk" CHECK ("paying_scope" IN ('instance', 'account', 'user')),
	CONSTRAINT "llm_calls_request_id_chk" CHECK (char_length(request_id) <= 64),
	CONSTRAINT "llm_calls_attempt_chk" CHECK (attempt BETWEEN 1 AND 20),
	CONSTRAINT "llm_calls_prompt_version_chk" CHECK (char_length(prompt_version) <= 20),
	CONSTRAINT "llm_calls_image_count_chk" CHECK (image_count >= 0),
	CONSTRAINT "llm_calls_finish_reason_chk" CHECK (char_length(finish_reason) <= 40),
	CONSTRAINT "llm_calls_error_code_chk" CHECK (error_code ~ '^[a-z0-9_]{1,40}$'),
	CONSTRAINT "llm_calls_cost_pair_chk" CHECK ((cost_amount IS NULL) = (cost_currency IS NULL)),
	CONSTRAINT "llm_calls_not_sent_chk" CHECK (sent OR (input_tokens IS NULL AND output_tokens IS NULL AND cost_amount IS NULL)),
	CONSTRAINT "llm_calls_sent_source_chk" CHECK (sent = (cost_source <> 'not_sent')),
	CONSTRAINT "llm_calls_price_chk" CHECK (cost_source NOT IN ('price_table', 'price_table_later') OR price_id IS NOT NULL),
	CONSTRAINT "llm_calls_payer_chk" CHECK (CASE paying_scope
            WHEN 'instance' THEN paying_account_id IS NULL AND paying_user_id IS NULL
            WHEN 'account' THEN paying_account_id IS NOT NULL AND paying_user_id IS NULL
            ELSE paying_user_id IS NOT NULL AND paying_account_id IS NULL END)
) PARTITION BY RANGE ("at");
--> statement-breakpoint
ALTER TABLE "admin_alerts" DROP CONSTRAINT "admin_alerts_kind_chk";--> statement-breakpoint
ALTER TABLE "ai_breakers" ADD CONSTRAINT "ai_breakers_provider_id_ai_providers_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."ai_providers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai_budgets" ADD CONSTRAINT "ai_budgets_owner_account_id_owner_accounts_id_fk" FOREIGN KEY ("owner_account_id") REFERENCES "public"."owner_accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai_budgets" ADD CONSTRAINT "ai_budgets_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai_budgets" ADD CONSTRAINT "ai_budgets_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai_budgets" ADD CONSTRAINT "ai_budgets_cap_currency_currencies_code_fk" FOREIGN KEY ("cap_currency") REFERENCES "public"."currencies"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai_model_prices" ADD CONSTRAINT "ai_model_prices_currency_currencies_code_fk" FOREIGN KEY ("currency") REFERENCES "public"."currencies"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai_provider_limits" ADD CONSTRAINT "ai_provider_limits_provider_id_ai_providers_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."ai_providers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai_providers" ADD CONSTRAINT "ai_providers_owner_account_id_owner_accounts_id_fk" FOREIGN KEY ("owner_account_id") REFERENCES "public"."owner_accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai_providers" ADD CONSTRAINT "ai_providers_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ai_budgets_account_idx" ON "ai_budgets" USING btree ("owner_account_id");--> statement-breakpoint
CREATE INDEX "ai_budgets_location_idx" ON "ai_budgets" USING btree ("location_id");--> statement-breakpoint
CREATE INDEX "ai_budgets_user_idx" ON "ai_budgets" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "ai_budgets_paused_idx" ON "ai_budgets" USING btree ("paused_until") WHERE paused_until IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "ai_model_prices_current_uq" ON "ai_model_prices" USING btree ("provider_kind","model") WHERE superseded_at IS NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "ai_providers_active_uq" ON "ai_providers" USING btree ("scope",coalesce(owner_account_id, user_id, '00000000-0000-0000-0000-000000000000'::uuid)) WHERE disabled_at IS NULL;--> statement-breakpoint
CREATE INDEX "ai_providers_account_idx" ON "ai_providers" USING btree ("owner_account_id");--> statement-breakpoint
CREATE INDEX "ai_providers_user_idx" ON "ai_providers" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "ai_usage_months_owner_idx" ON "ai_usage_months" USING btree ("owner_account_id","month");--> statement-breakpoint
CREATE INDEX "ai_usage_months_location_idx" ON "ai_usage_months" USING btree ("location_id","month");--> statement-breakpoint
CREATE INDEX "ai_usage_months_user_idx" ON "ai_usage_months" USING btree ("user_id","month");--> statement-breakpoint
CREATE INDEX "ai_usage_months_payer_idx" ON "ai_usage_months" USING btree ("paying_account_id","month");--> statement-breakpoint
CREATE INDEX "ai_usage_windows_start_idx" ON "ai_usage_windows" USING btree ("window_kind","window_start");--> statement-breakpoint
CREATE INDEX "llm_calls_user_idx" ON "llm_calls" USING btree ("user_id","at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "llm_calls_location_idx" ON "llm_calls" USING btree ("location_id","at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "llm_calls_owner_idx" ON "llm_calls" USING btree ("owner_account_id","at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "llm_calls_payer_idx" ON "llm_calls" USING btree ("paying_account_id","at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "llm_calls_instance_idx" ON "llm_calls" USING btree ("at" DESC NULLS LAST) WHERE paying_scope = 'instance';--> statement-breakpoint
CREATE INDEX "llm_calls_thing_idx" ON "llm_calls" USING btree ("thing_id","at" DESC NULLS LAST) WHERE thing_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX "llm_calls_extraction_idx" ON "llm_calls" USING btree ("extraction_id") WHERE extraction_id IS NOT NULL;--> statement-breakpoint
ALTER TABLE "admin_alerts" ADD CONSTRAINT "admin_alerts_kind_chk" CHECK ("kind" IN ('failed_jobs_rising', 'audit_default_partition', 'llm_default_partition', 'ai_instance_cap_warning', 'ai_instance_cap_reached', 'ai_instance_key_rejected', 'backup_failed'));