-- Generated by drizzle-kit (the three columns), then edited by hand below: an output-token
-- (OTPM) limit per key, learned from the provider's 429 and paced on (step-3 T9; ai/pacing.ts).
-- Groq documents only TPM and RPD headers; an organisation's OTPM limit shows only in the 429
-- that enforces it ("… on output tokens per minute (OTPM): Limit 1000, Used 997, Requested 192.
-- Please try again in 11.34s."). The pacer stores it here and counts each call's output in a
-- one-minute window, so the next call waits instead of drawing the 429.
--   - kept.ai_observe(provider, breaker, limits): `limits` may now carry `output`: {tokens} (a
--     call's output, counted once a limit is known) or {learned: {limit, used, freeInMs}} (a 429
--     naming the limit: the window is set to end when the provider said). The token-window
--     columns are written only when `limits` has them.
--   - kept.ai_key_admit(provider, estimate, job, output): a fourth argument, the call's expected
--     output (default 0); over the learned limit in the current window: sleep up to 10 s in
--     place, else hold until the window ends (`limits`), as for the token window.
ALTER TABLE "ai_provider_limits" ADD COLUMN "output_limit_tokens" integer;--> statement-breakpoint
ALTER TABLE "ai_provider_limits" ADD COLUMN "output_used" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "ai_provider_limits" ADD COLUMN "output_window_start" timestamp with time zone;--> statement-breakpoint
CREATE OR REPLACE FUNCTION kept.ai_observe(p_provider uuid, p_breaker jsonb, p_limits jsonb) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE
  o jsonb := p_limits->'output';
  learned jsonb := p_limits->'output'->'learned';
BEGIN
  IF NOT kept.ai_provider_reachable(p_provider) THEN
    RAISE EXCEPTION 'no such provider of yours' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF p_breaker IS NOT NULL THEN
    INSERT INTO public.ai_breakers AS b (provider_id, reason, until, trips, recent_errors,
                                         updated_at)
    VALUES (p_provider, p_breaker->>'reason', (p_breaker->>'until')::timestamptz,
            coalesce((p_breaker->>'trips')::int, 0),
            coalesce(ARRAY(SELECT jsonb_array_elements_text(p_breaker->'recentErrors')::timestamptz),
                     '{}'),
            now())
    ON CONFLICT (provider_id) DO UPDATE
      SET reason = EXCLUDED.reason, until = EXCLUDED.until, trips = EXCLUDED.trips,
          recent_errors = EXCLUDED.recent_errors, updated_at = EXCLUDED.updated_at;
  END IF;
  IF p_limits ?| ARRAY['limitTokens', 'remainingTokens', 'resetAt'] THEN
    INSERT INTO public.ai_provider_limits (provider_id, limit_tokens, remaining_tokens, reset_at,
                                           updated_at)
    VALUES (p_provider, (p_limits->>'limitTokens')::int, (p_limits->>'remainingTokens')::int,
            (p_limits->>'resetAt')::timestamptz, now())
    ON CONFLICT (provider_id) DO UPDATE
      SET limit_tokens = EXCLUDED.limit_tokens, remaining_tokens = EXCLUDED.remaining_tokens,
          reset_at = EXCLUDED.reset_at, updated_at = EXCLUDED.updated_at;
  END IF;
  IF learned IS NOT NULL THEN
    INSERT INTO public.ai_provider_limits AS l (provider_id, output_limit_tokens, output_used,
                                                output_window_start, updated_at)
    VALUES (p_provider, (learned->>'limit')::int, greatest(coalesce((learned->>'used')::int, 0), 0),
            now() + make_interval(secs => (least(coalesce((learned->>'freeInMs')::numeric, 60000),
                                                 60000) / 1000.0)::double precision)
                  - interval '1 minute',
            now())
    ON CONFLICT (provider_id) DO UPDATE
      SET output_limit_tokens = EXCLUDED.output_limit_tokens, output_used = EXCLUDED.output_used,
          output_window_start = EXCLUDED.output_window_start, updated_at = EXCLUDED.updated_at;
  ELSIF o IS NOT NULL THEN
    -- Counted only once a limit is known (a key without one is paced by its headers alone).
    UPDATE public.ai_provider_limits l
       SET output_used = CASE
             WHEN l.output_window_start IS NULL OR l.output_window_start <= now() - interval '1 minute'
             THEN greatest(coalesce((o->>'tokens')::int, 0), 0)
             ELSE l.output_used + greatest(coalesce((o->>'tokens')::int, 0), 0) END,
           output_window_start = CASE
             WHEN l.output_window_start IS NULL OR l.output_window_start <= now() - interval '1 minute'
             THEN now() ELSE l.output_window_start END,
           updated_at = now()
     WHERE l.provider_id = p_provider AND l.output_limit_tokens IS NOT NULL;
  END IF;
END $$;
--> statement-breakpoint
DROP FUNCTION kept.ai_key_admit(uuid, integer, text);
--> statement-breakpoint
CREATE FUNCTION kept.ai_key_admit(p_provider uuid, p_estimate integer, p_job text,
                                  p_output integer DEFAULT 0)
RETURNS TABLE (ok boolean, kind text, until timestamptz, reason text, slot integer,
               wait_ms integer)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE
  pkind text;
  br public.ai_breakers%ROWTYPE;
  lim public.ai_provider_limits%ROWTYPE;
  lease text := 'key:' || p_provider;
  n integer;
  took integer;
  ms integer;
  ends timestamptz;
BEGIN
  IF p_job IS NULL OR NOT kept.ai_provider_reachable(p_provider) THEN
    RAISE EXCEPTION 'no such provider of yours' USING ERRCODE = 'insufficient_privilege';
  END IF;
  SELECT p.kind INTO pkind FROM public.ai_providers p WHERE p.id = p_provider;
  PERFORM pg_advisory_xact_lock(hashtext('kept.ai'), hashtext(lease));
  SELECT * INTO br FROM public.ai_breakers b WHERE b.provider_id = p_provider;
  IF br.reason IS NOT NULL AND br.until > now() THEN
    RETURN QUERY SELECT false, 'hold'::text, br.until, br.reason, NULL::integer, NULL::integer;
    RETURN;
  END IF;
  SELECT * INTO lim FROM public.ai_provider_limits l WHERE l.provider_id = p_provider;
  IF lim.remaining_tokens IS NOT NULL AND lim.reset_at > now()
     AND lim.remaining_tokens < coalesce(p_estimate, 0) THEN
    ms := ceil(extract(epoch FROM lim.reset_at - now()) * 1000)::int;
    IF ms <= 10000 THEN
      RETURN QUERY SELECT false, 'sleep'::text, lim.reset_at, 'limits'::text, NULL::integer, ms;
    ELSE
      RETURN QUERY SELECT false, 'hold'::text, lim.reset_at, 'limits'::text, NULL::integer,
                          NULL::integer;
    END IF;
    RETURN;
  END IF;
  ends := lim.output_window_start + interval '1 minute';
  IF lim.output_limit_tokens IS NOT NULL AND ends > now()
     AND lim.output_used + greatest(coalesce(p_output, 0), 0) > lim.output_limit_tokens THEN
    ms := ceil(extract(epoch FROM ends - now()) * 1000)::int;
    IF ms <= 10000 THEN
      RETURN QUERY SELECT false, 'sleep'::text, ends, 'limits'::text, NULL::integer, ms;
    ELSE
      RETURN QUERY SELECT false, 'hold'::text, ends, 'limits'::text, NULL::integer, NULL::integer;
    END IF;
    RETURN;
  END IF;
  n := CASE pkind WHEN 'groq' THEN 1 ELSE 2 END;
  SELECT s INTO took FROM generate_series(1, n) AS s
   WHERE NOT EXISTS (SELECT 1 FROM public.ai_leases l
                      WHERE l.lease_key = lease AND l.slot = s AND l.lease_until > now()
                        AND l.job_id <> p_job)
   ORDER BY s LIMIT 1;
  IF took IS NULL THEN
    RETURN QUERY SELECT false, 'hold'::text, now() + interval '15 seconds', 'concurrency'::text,
                        NULL::integer, NULL::integer;
    RETURN;
  END IF;
  INSERT INTO public.ai_leases (lease_key, slot, job_id, lease_until)
  VALUES (lease, took, p_job, now() + interval '5 minutes')
  ON CONFLICT ON CONSTRAINT ai_leases_pk DO UPDATE
    SET job_id = EXCLUDED.job_id, lease_until = EXCLUDED.lease_until;
  RETURN QUERY SELECT true, 'ok'::text, NULL::timestamptz, NULL::text, took, NULL::integer;
END $$;
--> statement-breakpoint
REVOKE EXECUTE ON FUNCTION kept.ai_key_admit(uuid, integer, text, integer) FROM PUBLIC;
--> statement-breakpoint
GRANT EXECUTE ON FUNCTION kept.ai_key_admit(uuid, integer, text, integer) TO kept_app, kept_system;
