-- Generated by drizzle-kit (the tables, the column, the index and the source CHECK), then
-- edited by hand below. Step 3, task 17a: own codes (D208; engineering spec §1.10, §7.16).
--   1. legacy_codes gains the source `own`: the household's own codes, typed, numbered or
--      imported, resolved like any legacy code (scan, search, the jump box). Unique per location
--      by the primary key (source `own`, collection ''); the server also refuses a code the
--      location has under another source. `legacy_codes_any_code_idx` answers a code looked up
--      whatever its source.
--   2. own_code_settings (numbering and the format rule; read by members, written by owners and
--      admins) and own_code_counters (the numbering's counters: read by members, moved only
--      through the door).
--   3. kept.next_own_code(location): the next numbered code, the counter row incremented under
--      its lock in the caller's transaction, skipping a code the location already has. A number
--      is never taken twice, even after its code is deleted.
--   4. A new confirmed thing gets a numbered code when the location numbers them
--      (kept.number_new_thing, a constraint trigger AFTER INSERT OR UPDATE OF review_state,
--      deferred to the end of the transaction: a draft is numbered when it is confirmed, and a
--      thing that has an own code by then gets none: an import row's own code, a place turned
--      into a box keeping the place's). Deferred, the counter's lock is held only while the
--      transaction commits.
--   5. Removals reach phones: sync_tombstones gains entity_key, the text key of a removed code
--      or legacy code (`legacyCodeKey()`: location:source:collection:code), with
--      entity_id = md5(entity_key)::uuid so the primary key still holds one row per key.
--      A deleted legacy code writes its tombstone (kept.tombstone_legacy_code), unless its
--      location is going too; one that arrives clears it (kept.clear_code_tombstone_on_arrival).
-- test/leak.test.ts and src/db/migrate.test.ts list the functions; test/leak-capture.ts fills the
-- tables.
CREATE TABLE "own_code_counters" (
	"location_id" uuid NOT NULL,
	"prefix" text NOT NULL,
	"last_number" bigint DEFAULT 0 NOT NULL,
	CONSTRAINT "own_code_counters_pk" PRIMARY KEY("location_id","prefix"),
	CONSTRAINT "own_code_counters_number_chk" CHECK (last_number >= 0)
);
--> statement-breakpoint
CREATE TABLE "own_code_settings" (
	"location_id" uuid PRIMARY KEY NOT NULL,
	"numbering" boolean DEFAULT false NOT NULL,
	"prefix" text DEFAULT '' NOT NULL,
	"pad" smallint DEFAULT 4 NOT NULL,
	"rule_pattern" text,
	"rule_message" text,
	"rule_example" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"row_version" integer DEFAULT 1 NOT NULL,
	"change_seq" bigint,
	CONSTRAINT "own_code_settings_prefix_chk" CHECK (char_length(prefix) <= 20 AND prefix = upper(btrim(prefix))),
	CONSTRAINT "own_code_settings_pad_chk" CHECK (pad BETWEEN 1 AND 8),
	CONSTRAINT "own_code_settings_rule_chk" CHECK (num_nonnulls(rule_pattern, rule_message, rule_example) IN (0, 3)
          AND char_length(rule_pattern) BETWEEN 1 AND 200
          AND char_length(rule_message) BETWEEN 1 AND 200
          AND char_length(rule_example) BETWEEN 1 AND 100)
);
--> statement-breakpoint
ALTER TABLE "legacy_codes" DROP CONSTRAINT "legacy_codes_source_chk";--> statement-breakpoint
ALTER TABLE "sync_tombstones" ADD COLUMN "entity_key" text;--> statement-breakpoint
ALTER TABLE "own_code_counters" ADD CONSTRAINT "own_code_counters_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "own_code_settings" ADD CONSTRAINT "own_code_settings_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "legacy_codes_any_code_idx" ON "legacy_codes" USING btree ("code");--> statement-breakpoint
ALTER TABLE "legacy_codes" ADD CONSTRAINT "legacy_codes_source_chk" CHECK ("source" IN ('homebox', 'csv', 'own'));--> statement-breakpoint
ALTER TABLE "sync_tombstones" ADD CONSTRAINT "sync_tombstones_key_chk" CHECK ((entity_type IN ('code', 'legacy_code')) = (entity_key IS NOT NULL)
          AND (entity_key IS NULL
               OR (char_length(entity_key) <= 400 AND entity_id = md5(entity_key)::uuid)));
--> statement-breakpoint

-- 2. Row-level security and privileges -----------------------------------------------------------
DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['own_code_settings', 'own_code_counters'] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format(
      'CREATE POLICY owner_all ON public.%I FOR ALL TO kept_owner USING (true) WITH CHECK (true)',
      t);
    EXECUTE format('REVOKE ALL ON public.%I FROM kept_system', t);
  END LOOP;
END $$;
--> statement-breakpoint
-- The counters: read by members (settings shows the next number), moved only by
-- kept.next_own_code().
REVOKE INSERT, UPDATE, DELETE ON public.own_code_counters FROM kept_app;
--> statement-breakpoint
CREATE POLICY app_select ON public.own_code_counters FOR SELECT TO kept_app
  USING (location_id IN (SELECT kept.visible_location_ids()));
--> statement-breakpoint
-- The settings: every member reads them; owners and admins write them. Never deleted (off is a
-- row with numbering false and no rule).
REVOKE UPDATE, DELETE ON public.own_code_settings FROM kept_app;
--> statement-breakpoint
GRANT UPDATE (numbering, prefix, pad, rule_pattern, rule_message, rule_example, updated_at,
              row_version) ON public.own_code_settings TO kept_app;
--> statement-breakpoint
CREATE POLICY app_select ON public.own_code_settings FOR SELECT TO kept_app
  USING (location_id IN (SELECT kept.visible_location_ids()));
--> statement-breakpoint
CREATE POLICY app_insert ON public.own_code_settings FOR INSERT TO kept_app
  WITH CHECK (location_id IN (SELECT kept.admin_location_ids()));
--> statement-breakpoint
CREATE POLICY app_update ON public.own_code_settings FOR UPDATE TO kept_app
  USING (location_id IN (SELECT kept.admin_location_ids()))
  WITH CHECK (location_id IN (SELECT kept.admin_location_ids()));
--> statement-breakpoint
CREATE TRIGGER touch_row BEFORE INSERT OR UPDATE ON public.own_code_settings
  FOR EACH ROW EXECUTE FUNCTION kept.touch_row();
--> statement-breakpoint

-- 3. The next numbered code ----------------------------------------------------------------------
-- Null when the location doesn't number its codes. The INSERT … ON CONFLICT DO UPDATE takes the
-- counter row's lock until the caller's transaction ends, so parallel creates number one after
-- another; a rolled-back create gives its number back with the rollback (nothing else saw it).
CREATE FUNCTION kept.next_own_code(p_location uuid) RETURNS text
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE
  s public.own_code_settings%ROWTYPE;
  n bigint;
  digits text;
  candidate text;
  tries integer := 0;
BEGIN
  IF p_location IS NULL
     OR NOT EXISTS (SELECT 1 FROM kept.writable_location_ids() w WHERE w = p_location) THEN
    RAISE EXCEPTION 'no such location of yours' USING ERRCODE = 'insufficient_privilege';
  END IF;
  SELECT * INTO s FROM public.own_code_settings o WHERE o.location_id = p_location;
  IF NOT FOUND OR NOT s.numbering THEN
    RETURN NULL;
  END IF;
  LOOP
    INSERT INTO public.own_code_counters AS c (location_id, prefix, last_number)
    VALUES (p_location, s.prefix, 1)
    ON CONFLICT (location_id, prefix) DO UPDATE SET last_number = c.last_number + 1
    RETURNING c.last_number INTO n;
    digits := n::text;
    -- lpad() would cut a number longer than the padding: GAR-10000 stays whole.
    IF char_length(digits) < s.pad THEN
      digits := lpad(digits, s.pad, '0');
    END IF;
    candidate := s.prefix || digits;
    EXIT WHEN NOT EXISTS (SELECT 1 FROM public.legacy_codes g
                           WHERE g.location_id = p_location AND g.code = candidate);
    tries := tries + 1;
    IF tries >= 10000 THEN
      RAISE EXCEPTION 'every next number is taken' USING ERRCODE = 'check_violation',
        CONSTRAINT = 'own_code_numbers_taken';
    END IF;
  END LOOP;
  RETURN candidate;
END $$;
--> statement-breakpoint
REVOKE EXECUTE ON FUNCTION kept.next_own_code(uuid) FROM PUBLIC, kept_system;
--> statement-breakpoint

-- 4. A new confirmed thing is numbered -----------------------------------------------------------
-- A definer, so the counter's door is reached as its owner; it numbers only in a location the
-- writer may write (a job with no person numbers nothing). It runs at commit, so it reads the
-- thing as it is then: gone, trashed or back to a draft, it numbers nothing.
CREATE FUNCTION kept.number_new_thing() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE
  t record;
  code text;
BEGIN
  IF TG_OP = 'UPDATE' AND OLD.review_state = 'confirmed' THEN
    RETURN NULL;
  END IF;
  SELECT th.id, th.location_id INTO t FROM public.things th
   WHERE th.id = NEW.id AND th.review_state = 'confirmed' AND th.deleted_at IS NULL;
  IF NOT FOUND THEN
    RETURN NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.own_code_settings o
                  WHERE o.location_id = t.location_id AND o.numbering) THEN
    RETURN NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM kept.writable_location_ids() w WHERE w = t.location_id) THEN
    RETURN NULL;
  END IF;
  IF EXISTS (SELECT 1 FROM public.legacy_codes g
              WHERE g.location_id = t.location_id AND g.source = 'own' AND g.thing_id = t.id) THEN
    RETURN NULL;
  END IF;
  code := kept.next_own_code(t.location_id);
  IF code IS NOT NULL THEN
    INSERT INTO public.legacy_codes (location_id, source, source_collection, code, thing_id)
    VALUES (t.location_id, 'own', '', code, t.id);
  END IF;
  RETURN NULL;
END $$;
--> statement-breakpoint
REVOKE EXECUTE ON FUNCTION kept.number_new_thing() FROM PUBLIC, kept_app, kept_system;
--> statement-breakpoint
CREATE CONSTRAINT TRIGGER things_own_code_number
  AFTER INSERT OR UPDATE OF review_state ON public.things
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION kept.number_new_thing();
--> statement-breakpoint

-- 5. Removals reach phones -----------------------------------------------------------------------
-- The key is shared/src/sync.ts legacyCodeKey(): `<location>:<source>:<collection>:<code>`.
-- Definers: a tombstone is bookkeeping about the row that went or came, whoever wrote it (a person,
-- a door, a job), so it never depends on the writer's policies on sync_tombstones.
CREATE FUNCTION kept.tombstone_legacy_code() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE
  k text := OLD.location_id::text || ':' || OLD.source || ':' || OLD.source_collection || ':'
            || OLD.code;
BEGIN
  -- A location being deleted takes its tombstones with it; its phones drop it as revoked.
  IF NOT EXISTS (SELECT 1 FROM public.locations l WHERE l.id = OLD.location_id) THEN
    RETURN NULL;
  END IF;
  INSERT INTO public.sync_tombstones (location_id, entity_type, entity_id, entity_key)
  VALUES (OLD.location_id, 'legacy_code', md5(k)::uuid, k)
  ON CONFLICT (location_id, entity_type, entity_id) DO UPDATE SET updated_at = now();
  RETURN NULL;
END $$;
--> statement-breakpoint
REVOKE EXECUTE ON FUNCTION kept.tombstone_legacy_code() FROM PUBLIC, kept_app, kept_system;
--> statement-breakpoint
CREATE TRIGGER legacy_codes_tombstone AFTER DELETE ON public.legacy_codes
  FOR EACH ROW EXECUTE FUNCTION kept.tombstone_legacy_code();
--> statement-breakpoint
CREATE FUNCTION kept.clear_code_tombstone_on_arrival() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
BEGIN
  DELETE FROM public.sync_tombstones z
   WHERE z.location_id = NEW.location_id AND z.entity_type = 'legacy_code'
     AND z.entity_id = md5(NEW.location_id::text || ':' || NEW.source || ':'
                           || NEW.source_collection || ':' || NEW.code)::uuid;
  RETURN NULL;
END $$;
--> statement-breakpoint
REVOKE EXECUTE ON FUNCTION kept.clear_code_tombstone_on_arrival() FROM PUBLIC, kept_app, kept_system;
--> statement-breakpoint
CREATE TRIGGER legacy_codes_tombstone_arrival AFTER INSERT OR UPDATE OF location_id ON public.legacy_codes
  FOR EACH ROW EXECUTE FUNCTION kept.clear_code_tombstone_on_arrival();
