-- Generated by drizzle-kit, then edited by hand in one place: drizzle drops and re-adds a generated
-- column whose expression changes; on the partitioned ledger (0039) the expression is changed in
-- place (Postgres 17+ SET EXPRESSION, which rewrites each partition), keeping the column's place
-- and its rows. Step 7 (D69, plan Q21): `enrich_aliases` counts against the extraction budget.
ALTER TABLE "llm_calls" DROP CONSTRAINT "llm_calls_task_chk";--> statement-breakpoint
ALTER TABLE "llm_calls" ALTER COLUMN "budget_task" SET EXPRESSION AS (CASE WHEN task LIKE 'extract\_%' OR task = 'enrich_aliases' THEN 'extraction'
               WHEN task LIKE 'assistant\_%' THEN 'assistant'
               WHEN task LIKE 'embed\_%' THEN 'embeddings' ELSE 'test' END);--> statement-breakpoint
ALTER TABLE "llm_calls" ADD CONSTRAINT "llm_calls_task_chk" CHECK ("task" IN ('extract_thing', 'extract_receipt', 'extract_label', 'extract_reading', 'assistant_turn', 'assistant_followup', 'embed_thing', 'embed_query', 'connection_test', 'enrich_aliases'));
