-- Generated by drizzle-kit, then edited by hand in one place: existing completions take the time
-- the scan used to stand in for theirs (their record's latest of created_at and updated_at), so
-- no reminder closes differently because of the migration.
ALTER TABLE "service_completions" ADD COLUMN "created_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
UPDATE "service_completions" c SET "created_at" = greatest(r.created_at, r.updated_at)
  FROM "service_records" r WHERE r.id = c.service_record_id;
