-- Generated by drizzle-kit, then edited by hand in one place: the column grant at the end.
-- Step 6: an extraction remembers the output-token cap its retry runs at (learned from a call cut
-- off for length). Schema only here; the retry that reads and sets it is step 6's to finish.
ALTER TABLE "extractions" ADD COLUMN "output_cap" integer;--> statement-breakpoint
ALTER TABLE "extractions" ADD CONSTRAINT "extractions_output_cap_chk" CHECK (output_cap BETWEEN 64 AND 200000);--> statement-breakpoint
GRANT UPDATE (output_cap) ON public.extractions TO kept_app;
