-- Generated by drizzle-kit. Step 7 T14: import_source_ids remembers the step 4–6 entities the Kept
-- import writes (loans, claims, incidents, valuations, expiring documents, fuel entries, service
-- lines), so a source id of any of them maps to the row it became.
ALTER TABLE "import_source_ids" DROP CONSTRAINT "import_source_ids_entity_type_chk";--> statement-breakpoint
ALTER TABLE "import_source_ids" ADD CONSTRAINT "import_source_ids_entity_type_chk" CHECK ("entity_type" IN ('thing', 'place', 'purchase', 'attachment', 'file', 'tag', 'type', 'type_field', 'brand', 'vendor', 'person', 'template', 'meter', 'reading', 'box_check', 'stock_rule', 'warranty', 'service_record', 'schedule', 'loan', 'claim', 'incident', 'valuation', 'expiring_document', 'fuel_entry', 'service_line'));