-- Generated by drizzle-kit. Step 7 T17: low-stock reminders: the day a thing ran low (0104 keeps it)
-- and the `stock` notification preference kind.
ALTER TABLE "notification_preferences" DROP CONSTRAINT "notification_preferences_kind_chk";--> statement-breakpoint
ALTER TABLE "stock_rules" ADD COLUMN "low_since" date;--> statement-breakpoint
ALTER TABLE "notification_preferences" ADD CONSTRAINT "notification_preferences_kind_chk" CHECK ("kind" IN ('schedule', 'warranty', 'registration', 'document', 'loan', 'thing_expiry', 'reading_stale', 'stock', 'membership', 'ai_cap', 'ai_summary'));