/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PrintRouteImport } from './routes/_print'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppCaptureRouteImport } from './routes/_app/capture'
import { Route as AppConsumablesRouteImport } from './routes/_app/consumables'
import { Route as AppExpiringRouteImport } from './routes/_app/expiring'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppIncidentsRouteImport } from './routes/_app/incidents'
import { Route as AppLabelsRouteImport } from './routes/_app/labels'
import { Route as AppLendingRouteImport } from './routes/_app/lending'
import { Route as AppMoreRouteImport } from './routes/_app/more'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppPaperworkRouteImport } from './routes/_app/paperwork'
import { Route as AppScanRouteImport } from './routes/_app/scan'
import { Route as AppSchedulesRouteImport } from './routes/_app/schedules'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppTrashRouteImport } from './routes/_app/trash'
import { Route as AppVehiclesRouteImport } from './routes/_app/vehicles'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as AuthEmailChangeRouteImport } from './routes/auth/email-change'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as SigninIndexRouteImport } from './routes/signin/index'
import { Route as SigninCodeRouteImport } from './routes/signin/code'
import { Route as SigninTwoFactorRouteImport } from './routes/signin/two-factor'
import { Route as AppAAssetIdRouteImport } from './routes/_app/a.$assetId'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin.index'
import { Route as AppAdminAdminsRouteImport } from './routes/_app/admin.admins'
import { Route as AppAdminAiRouteImport } from './routes/_app/admin.ai'
import { Route as AppAdminAlertsRouteImport } from './routes/_app/admin.alerts'
import { Route as AppAdminBackupsRouteImport } from './routes/_app/admin.backups'
import { Route as AppAdminCurrenciesRouteImport } from './routes/_app/admin.currencies'
import { Route as AppAdminJobsRouteImport } from './routes/_app/admin.jobs'
import { Route as AppAdminSettingsRouteImport } from './routes/_app/admin.settings'
import { Route as AppAdminStatusRouteImport } from './routes/_app/admin.status'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin.users'
import { Route as AppAssistantIndexRouteImport } from './routes/_app/assistant.index'
import { Route as AppAssistantThreadIdRouteImport } from './routes/_app/assistant.$threadId'
import { Route as AppBoxCheckIdRouteImport } from './routes/_app/box-check.$id'
import { Route as AppBrandsIdRouteImport } from './routes/_app/brands.$id'
import { Route as AppIncidentsIdRouteImport } from './routes/_app/incidents.$id'
import { Route as AppItemUuidRouteImport } from './routes/_app/item.$uuid'
import { Route as AppLCodeRouteImport } from './routes/_app/l.$code'
import { Route as AppLocIdRouteImport } from './routes/_app/loc.$id'
import { Route as AppLocationUuidRouteImport } from './routes/_app/location.$uuid'
import { Route as AppLocationsNewRouteImport } from './routes/_app/locations.new'
import { Route as AppPIdRouteImport } from './routes/_app/p.$id'
import { Route as AppPeopleIdRouteImport } from './routes/_app/people.$id'
import { Route as AppReportsKindRouteImport } from './routes/_app/reports.$kind'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings.index'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings.account'
import { Route as AppSettingsAiRouteImport } from './routes/_app/settings.ai'
import { Route as AppSettingsConnectionsRouteImport } from './routes/_app/settings.connections'
import { Route as AppSettingsDeviceRouteImport } from './routes/_app/settings.device'
import { Route as AppSettingsDiagnosticsRouteImport } from './routes/_app/settings.diagnostics'
import { Route as AppSettingsExportRouteImport } from './routes/_app/settings.export'
import { Route as AppSettingsImportRouteImport } from './routes/_app/settings.import'
import { Route as AppSettingsLocationsRouteImport } from './routes/_app/settings.locations'
import { Route as AppSettingsTwoFactorRouteImport } from './routes/_app/settings.two-factor'
import { Route as AppTIdRouteImport } from './routes/_app/t.$id'
import { Route as AppTypesIdRouteImport } from './routes/_app/types.$id'
import { Route as AppVendorsIdRouteImport } from './routes/_app/vendors.$id'
import { Route as PrintLabelsBatchIdRouteImport } from './routes/_print/labels.$batchId'
import { Route as AppAdminAiUsageRouteImport } from './routes/_app/admin.ai.usage'
import { Route as AppSettingsAccountIndexRouteImport } from './routes/_app/settings.account.index'
import { Route as AppSettingsAccountBrandsRouteImport } from './routes/_app/settings.account.brands'
import { Route as AppSettingsAccountExchangeRatesRouteImport } from './routes/_app/settings.account.exchange-rates'
import { Route as AppSettingsAccountPeopleRouteImport } from './routes/_app/settings.account.people'
import { Route as AppSettingsAccountPlaceKindsRouteImport } from './routes/_app/settings.account.place-kinds'
import { Route as AppSettingsAccountTagsRouteImport } from './routes/_app/settings.account.tags'
import { Route as AppSettingsAccountTemplatesRouteImport } from './routes/_app/settings.account.templates'
import { Route as AppSettingsAccountTypesRouteImport } from './routes/_app/settings.account.types'
import { Route as AppSettingsAccountVendorsRouteImport } from './routes/_app/settings.account.vendors'
import { Route as AppSettingsAiUsageRouteImport } from './routes/_app/settings.ai.usage'
import { Route as AppSettingsMeAiRouteImport } from './routes/_app/settings.me.ai'
import { Route as AppSettingsMeNotificationsRouteImport } from './routes/_app/settings.me.notifications'
import { Route as AppSettingsLocationIdGeneralRouteImport } from './routes/_app/settings.location.$id.general'
import { Route as AppSettingsLocationIdInviteRouteImport } from './routes/_app/settings.location.$id.invite'
import { Route as AppSettingsLocationIdMembersRouteImport } from './routes/_app/settings.location.$id.members'
import { Route as AppSettingsLocationIdTrackRouteImport } from './routes/_app/settings.location.$id.track'
import { Route as AppSettingsLocationIdWebhooksRouteImport } from './routes/_app/settings.location.$id.webhooks'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/_print',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCaptureRoute = AppCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => AppRoute,
} as any)
const AppConsumablesRoute = AppConsumablesRouteImport.update({
  id: '/consumables',
  path: '/consumables',
  getParentRoute: () => AppRoute,
} as any)
const AppExpiringRoute = AppExpiringRouteImport.update({
  id: '/expiring',
  path: '/expiring',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppLabelsRoute = AppLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AppRoute,
} as any)
const AppLendingRoute = AppLendingRouteImport.update({
  id: '/lending',
  path: '/lending',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPaperworkRoute = AppPaperworkRouteImport.update({
  id: '/paperwork',
  path: '/paperwork',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppSchedulesRoute = AppSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppTrashRoute = AppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiclesRoute = AppVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppRoute,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEmailChangeRoute = AuthEmailChangeRouteImport.update({
  id: '/auth/email-change',
  path: '/auth/email-change',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninIndexRoute = SigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninCodeRoute = SigninCodeRouteImport.update({
  id: '/signin/code',
  path: '/signin/code',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninTwoFactorRoute = SigninTwoFactorRouteImport.update({
  id: '/signin/two-factor',
  path: '/signin/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAAssetIdRoute = AppAAssetIdRouteImport.update({
  id: '/a/$assetId',
  path: '/a/$assetId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAdminsRoute = AppAdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAiRoute = AppAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAlertsRoute = AppAdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBackupsRoute = AppAdminBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCurrenciesRoute = AppAdminCurrenciesRouteImport.update({
  id: '/currencies',
  path: '/currencies',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminJobsRoute = AppAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminStatusRoute = AppAdminStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAssistantIndexRoute = AppAssistantIndexRouteImport.update({
  id: '/assistant/',
  path: '/assistant/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantThreadIdRoute = AppAssistantThreadIdRouteImport.update({
  id: '/assistant/$threadId',
  path: '/assistant/$threadId',
  getParentRoute: () => AppRoute,
} as any)
const AppBoxCheckIdRoute = AppBoxCheckIdRouteImport.update({
  id: '/box-check/$id',
  path: '/box-check/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsIdRoute = AppBrandsIdRouteImport.update({
  id: '/brands/$id',
  path: '/brands/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsIdRoute = AppIncidentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppIncidentsRoute,
} as any)
const AppItemUuidRoute = AppItemUuidRouteImport.update({
  id: '/item/$uuid',
  path: '/item/$uuid',
  getParentRoute: () => AppRoute,
} as any)
const AppLCodeRoute = AppLCodeRouteImport.update({
  id: '/l/$code',
  path: '/l/$code',
  getParentRoute: () => AppRoute,
} as any)
const AppLocIdRoute = AppLocIdRouteImport.update({
  id: '/loc/$id',
  path: '/loc/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationUuidRoute = AppLocationUuidRouteImport.update({
  id: '/location/$uuid',
  path: '/location/$uuid',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsNewRoute = AppLocationsNewRouteImport.update({
  id: '/locations/new',
  path: '/locations/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPIdRoute = AppPIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleIdRoute = AppPeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsKindRoute = AppReportsKindRouteImport.update({
  id: '/reports/$kind',
  path: '/reports/$kind',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAiRoute = AppSettingsAiRouteImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsConnectionsRoute = AppSettingsConnectionsRouteImport.update({
  id: '/settings/connections',
  path: '/settings/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsDeviceRoute = AppSettingsDeviceRouteImport.update({
  id: '/settings/device',
  path: '/settings/device',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsDiagnosticsRoute = AppSettingsDiagnosticsRouteImport.update({
  id: '/settings/diagnostics',
  path: '/settings/diagnostics',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsExportRoute = AppSettingsExportRouteImport.update({
  id: '/settings/export',
  path: '/settings/export',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsImportRoute = AppSettingsImportRouteImport.update({
  id: '/settings/import',
  path: '/settings/import',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsLocationsRoute = AppSettingsLocationsRouteImport.update({
  id: '/settings/locations',
  path: '/settings/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTwoFactorRoute = AppSettingsTwoFactorRouteImport.update({
  id: '/settings/two-factor',
  path: '/settings/two-factor',
  getParentRoute: () => AppRoute,
} as any)
const AppTIdRoute = AppTIdRouteImport.update({
  id: '/t/$id',
  path: '/t/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTypesIdRoute = AppTypesIdRouteImport.update({
  id: '/types/$id',
  path: '/types/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsIdRoute = AppVendorsIdRouteImport.update({
  id: '/vendors/$id',
  path: '/vendors/$id',
  getParentRoute: () => AppRoute,
} as any)
const PrintLabelsBatchIdRoute = PrintLabelsBatchIdRouteImport.update({
  id: '/labels/$batchId',
  path: '/labels/$batchId',
  getParentRoute: () => PrintRoute,
} as any)
const AppAdminAiUsageRoute = AppAdminAiUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppAdminAiRoute,
} as any)
const AppSettingsAccountIndexRoute = AppSettingsAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsAccountRoute,
} as any)
const AppSettingsAccountBrandsRoute =
  AppSettingsAccountBrandsRouteImport.update({
    id: '/brands',
    path: '/brands',
    getParentRoute: () => AppSettingsAccountRoute,
  } as any)
const AppSettingsAccountExchangeRatesRoute =
  AppSettingsAccountExchangeRatesRouteImport.update({
    id: '/exchange-rates',
    path: '/exchange-rates',
    getParentRoute: () => AppSettingsAccountRoute,
  } as any)
const AppSettingsAccountPeopleRoute =
  AppSettingsAccountPeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => AppSettingsAccountRoute,
  } as any)
const AppSettingsAccountPlaceKindsRoute =
  AppSettingsAccountPlaceKindsRouteImport.update({
    id: '/place-kinds',
    path: '/place-kinds',
    getParentRoute: () => AppSettingsAccountRoute,
  } as any)
const AppSettingsAccountTagsRoute = AppSettingsAccountTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppSettingsAccountRoute,
} as any)
const AppSettingsAccountTemplatesRoute =
  AppSettingsAccountTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AppSettingsAccountRoute,
  } as any)
const AppSettingsAccountTypesRoute = AppSettingsAccountTypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => AppSettingsAccountRoute,
} as any)
const AppSettingsAccountVendorsRoute =
  AppSettingsAccountVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => AppSettingsAccountRoute,
  } as any)
const AppSettingsAiUsageRoute = AppSettingsAiUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppSettingsAiRoute,
} as any)
const AppSettingsMeAiRoute = AppSettingsMeAiRouteImport.update({
  id: '/settings/me/ai',
  path: '/settings/me/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsMeNotificationsRoute =
  AppSettingsMeNotificationsRouteImport.update({
    id: '/settings/me/notifications',
    path: '/settings/me/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsLocationIdGeneralRoute =
  AppSettingsLocationIdGeneralRouteImport.update({
    id: '/settings/location/$id/general',
    path: '/settings/location/$id/general',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsLocationIdInviteRoute =
  AppSettingsLocationIdInviteRouteImport.update({
    id: '/settings/location/$id/invite',
    path: '/settings/location/$id/invite',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsLocationIdMembersRoute =
  AppSettingsLocationIdMembersRouteImport.update({
    id: '/settings/location/$id/members',
    path: '/settings/location/$id/members',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsLocationIdTrackRoute =
  AppSettingsLocationIdTrackRouteImport.update({
    id: '/settings/location/$id/track',
    path: '/settings/location/$id/track',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsLocationIdWebhooksRoute =
  AppSettingsLocationIdWebhooksRouteImport.update({
    id: '/settings/location/$id/webhooks',
    path: '/settings/location/$id/webhooks',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/gallery': typeof GalleryRoute
  '/invite': typeof InviteRoute
  '/setup': typeof SetupRoute
  '/activity': typeof AppActivityRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/capture': typeof AppCaptureRoute
  '/consumables': typeof AppConsumablesRoute
  '/expiring': typeof AppExpiringRoute
  '/help': typeof AppHelpRoute
  '/inbox': typeof AppInboxRoute
  '/incidents': typeof AppIncidentsRouteWithChildren
  '/labels': typeof AppLabelsRoute
  '/lending': typeof AppLendingRoute
  '/more': typeof AppMoreRoute
  '/notifications': typeof AppNotificationsRoute
  '/paperwork': typeof AppPaperworkRoute
  '/scan': typeof AppScanRoute
  '/schedules': typeof AppSchedulesRoute
  '/search': typeof AppSearchRoute
  '/trash': typeof AppTrashRoute
  '/vehicles': typeof AppVehiclesRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/email-change': typeof AuthEmailChangeRoute
  '/auth/reset': typeof AuthResetRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/signin/code': typeof SigninCodeRoute
  '/signin/two-factor': typeof SigninTwoFactorRoute
  '/signin/': typeof SigninIndexRoute
  '/a/$assetId': typeof AppAAssetIdRoute
  '/admin/admins': typeof AppAdminAdminsRoute
  '/admin/ai': typeof AppAdminAiRouteWithChildren
  '/admin/alerts': typeof AppAdminAlertsRoute
  '/admin/backups': typeof AppAdminBackupsRoute
  '/admin/currencies': typeof AppAdminCurrenciesRoute
  '/admin/jobs': typeof AppAdminJobsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/status': typeof AppAdminStatusRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/assistant/$threadId': typeof AppAssistantThreadIdRoute
  '/box-check/$id': typeof AppBoxCheckIdRoute
  '/brands/$id': typeof AppBrandsIdRoute
  '/incidents/$id': typeof AppIncidentsIdRoute
  '/item/$uuid': typeof AppItemUuidRoute
  '/l/$code': typeof AppLCodeRoute
  '/loc/$id': typeof AppLocIdRoute
  '/location/$uuid': typeof AppLocationUuidRoute
  '/locations/new': typeof AppLocationsNewRoute
  '/p/$id': typeof AppPIdRoute
  '/people/$id': typeof AppPeopleIdRoute
  '/reports/$kind': typeof AppReportsKindRoute
  '/settings/account': typeof AppSettingsAccountRouteWithChildren
  '/settings/ai': typeof AppSettingsAiRouteWithChildren
  '/settings/connections': typeof AppSettingsConnectionsRoute
  '/settings/device': typeof AppSettingsDeviceRoute
  '/settings/diagnostics': typeof AppSettingsDiagnosticsRoute
  '/settings/export': typeof AppSettingsExportRoute
  '/settings/import': typeof AppSettingsImportRoute
  '/settings/locations': typeof AppSettingsLocationsRoute
  '/settings/two-factor': typeof AppSettingsTwoFactorRoute
  '/t/$id': typeof AppTIdRoute
  '/types/$id': typeof AppTypesIdRoute
  '/vendors/$id': typeof AppVendorsIdRoute
  '/labels/$batchId': typeof PrintLabelsBatchIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/assistant/': typeof AppAssistantIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/admin/ai/usage': typeof AppAdminAiUsageRoute
  '/settings/account/brands': typeof AppSettingsAccountBrandsRoute
  '/settings/account/exchange-rates': typeof AppSettingsAccountExchangeRatesRoute
  '/settings/account/people': typeof AppSettingsAccountPeopleRoute
  '/settings/account/place-kinds': typeof AppSettingsAccountPlaceKindsRoute
  '/settings/account/tags': typeof AppSettingsAccountTagsRoute
  '/settings/account/templates': typeof AppSettingsAccountTemplatesRoute
  '/settings/account/types': typeof AppSettingsAccountTypesRoute
  '/settings/account/vendors': typeof AppSettingsAccountVendorsRoute
  '/settings/ai/usage': typeof AppSettingsAiUsageRoute
  '/settings/me/ai': typeof AppSettingsMeAiRoute
  '/settings/me/notifications': typeof AppSettingsMeNotificationsRoute
  '/settings/account/': typeof AppSettingsAccountIndexRoute
  '/settings/location/$id/general': typeof AppSettingsLocationIdGeneralRoute
  '/settings/location/$id/invite': typeof AppSettingsLocationIdInviteRoute
  '/settings/location/$id/members': typeof AppSettingsLocationIdMembersRoute
  '/settings/location/$id/track': typeof AppSettingsLocationIdTrackRoute
  '/settings/location/$id/webhooks': typeof AppSettingsLocationIdWebhooksRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/gallery': typeof GalleryRoute
  '/invite': typeof InviteRoute
  '/setup': typeof SetupRoute
  '/activity': typeof AppActivityRoute
  '/capture': typeof AppCaptureRoute
  '/consumables': typeof AppConsumablesRoute
  '/expiring': typeof AppExpiringRoute
  '/help': typeof AppHelpRoute
  '/inbox': typeof AppInboxRoute
  '/incidents': typeof AppIncidentsRouteWithChildren
  '/labels': typeof AppLabelsRoute
  '/lending': typeof AppLendingRoute
  '/more': typeof AppMoreRoute
  '/notifications': typeof AppNotificationsRoute
  '/paperwork': typeof AppPaperworkRoute
  '/scan': typeof AppScanRoute
  '/schedules': typeof AppSchedulesRoute
  '/search': typeof AppSearchRoute
  '/trash': typeof AppTrashRoute
  '/vehicles': typeof AppVehiclesRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/email-change': typeof AuthEmailChangeRoute
  '/auth/reset': typeof AuthResetRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/signin/code': typeof SigninCodeRoute
  '/signin/two-factor': typeof SigninTwoFactorRoute
  '/signin': typeof SigninIndexRoute
  '/a/$assetId': typeof AppAAssetIdRoute
  '/admin/admins': typeof AppAdminAdminsRoute
  '/admin/ai': typeof AppAdminAiRouteWithChildren
  '/admin/alerts': typeof AppAdminAlertsRoute
  '/admin/backups': typeof AppAdminBackupsRoute
  '/admin/currencies': typeof AppAdminCurrenciesRoute
  '/admin/jobs': typeof AppAdminJobsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/status': typeof AppAdminStatusRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/assistant/$threadId': typeof AppAssistantThreadIdRoute
  '/box-check/$id': typeof AppBoxCheckIdRoute
  '/brands/$id': typeof AppBrandsIdRoute
  '/incidents/$id': typeof AppIncidentsIdRoute
  '/item/$uuid': typeof AppItemUuidRoute
  '/l/$code': typeof AppLCodeRoute
  '/loc/$id': typeof AppLocIdRoute
  '/location/$uuid': typeof AppLocationUuidRoute
  '/locations/new': typeof AppLocationsNewRoute
  '/p/$id': typeof AppPIdRoute
  '/people/$id': typeof AppPeopleIdRoute
  '/reports/$kind': typeof AppReportsKindRoute
  '/settings/ai': typeof AppSettingsAiRouteWithChildren
  '/settings/connections': typeof AppSettingsConnectionsRoute
  '/settings/device': typeof AppSettingsDeviceRoute
  '/settings/diagnostics': typeof AppSettingsDiagnosticsRoute
  '/settings/export': typeof AppSettingsExportRoute
  '/settings/import': typeof AppSettingsImportRoute
  '/settings/locations': typeof AppSettingsLocationsRoute
  '/settings/two-factor': typeof AppSettingsTwoFactorRoute
  '/t/$id': typeof AppTIdRoute
  '/types/$id': typeof AppTypesIdRoute
  '/vendors/$id': typeof AppVendorsIdRoute
  '/labels/$batchId': typeof PrintLabelsBatchIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/assistant': typeof AppAssistantIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/admin/ai/usage': typeof AppAdminAiUsageRoute
  '/settings/account/brands': typeof AppSettingsAccountBrandsRoute
  '/settings/account/exchange-rates': typeof AppSettingsAccountExchangeRatesRoute
  '/settings/account/people': typeof AppSettingsAccountPeopleRoute
  '/settings/account/place-kinds': typeof AppSettingsAccountPlaceKindsRoute
  '/settings/account/tags': typeof AppSettingsAccountTagsRoute
  '/settings/account/templates': typeof AppSettingsAccountTemplatesRoute
  '/settings/account/types': typeof AppSettingsAccountTypesRoute
  '/settings/account/vendors': typeof AppSettingsAccountVendorsRoute
  '/settings/ai/usage': typeof AppSettingsAiUsageRoute
  '/settings/me/ai': typeof AppSettingsMeAiRoute
  '/settings/me/notifications': typeof AppSettingsMeNotificationsRoute
  '/settings/account': typeof AppSettingsAccountIndexRoute
  '/settings/location/$id/general': typeof AppSettingsLocationIdGeneralRoute
  '/settings/location/$id/invite': typeof AppSettingsLocationIdInviteRoute
  '/settings/location/$id/members': typeof AppSettingsLocationIdMembersRoute
  '/settings/location/$id/track': typeof AppSettingsLocationIdTrackRoute
  '/settings/location/$id/webhooks': typeof AppSettingsLocationIdWebhooksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_print': typeof PrintRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/invite': typeof InviteRoute
  '/setup': typeof SetupRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/capture': typeof AppCaptureRoute
  '/_app/consumables': typeof AppConsumablesRoute
  '/_app/expiring': typeof AppExpiringRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/incidents': typeof AppIncidentsRouteWithChildren
  '/_app/labels': typeof AppLabelsRoute
  '/_app/lending': typeof AppLendingRoute
  '/_app/more': typeof AppMoreRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/paperwork': typeof AppPaperworkRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/schedules': typeof AppSchedulesRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/trash': typeof AppTrashRoute
  '/_app/vehicles': typeof AppVehiclesRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/email-change': typeof AuthEmailChangeRoute
  '/auth/reset': typeof AuthResetRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/signin/code': typeof SigninCodeRoute
  '/signin/two-factor': typeof SigninTwoFactorRoute
  '/_app/': typeof AppIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/_app/a/$assetId': typeof AppAAssetIdRoute
  '/_app/admin/admins': typeof AppAdminAdminsRoute
  '/_app/admin/ai': typeof AppAdminAiRouteWithChildren
  '/_app/admin/alerts': typeof AppAdminAlertsRoute
  '/_app/admin/backups': typeof AppAdminBackupsRoute
  '/_app/admin/currencies': typeof AppAdminCurrenciesRoute
  '/_app/admin/jobs': typeof AppAdminJobsRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/status': typeof AppAdminStatusRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/assistant/$threadId': typeof AppAssistantThreadIdRoute
  '/_app/box-check/$id': typeof AppBoxCheckIdRoute
  '/_app/brands/$id': typeof AppBrandsIdRoute
  '/_app/incidents/$id': typeof AppIncidentsIdRoute
  '/_app/item/$uuid': typeof AppItemUuidRoute
  '/_app/l/$code': typeof AppLCodeRoute
  '/_app/loc/$id': typeof AppLocIdRoute
  '/_app/location/$uuid': typeof AppLocationUuidRoute
  '/_app/locations/new': typeof AppLocationsNewRoute
  '/_app/p/$id': typeof AppPIdRoute
  '/_app/people/$id': typeof AppPeopleIdRoute
  '/_app/reports/$kind': typeof AppReportsKindRoute
  '/_app/settings/account': typeof AppSettingsAccountRouteWithChildren
  '/_app/settings/ai': typeof AppSettingsAiRouteWithChildren
  '/_app/settings/connections': typeof AppSettingsConnectionsRoute
  '/_app/settings/device': typeof AppSettingsDeviceRoute
  '/_app/settings/diagnostics': typeof AppSettingsDiagnosticsRoute
  '/_app/settings/export': typeof AppSettingsExportRoute
  '/_app/settings/import': typeof AppSettingsImportRoute
  '/_app/settings/locations': typeof AppSettingsLocationsRoute
  '/_app/settings/two-factor': typeof AppSettingsTwoFactorRoute
  '/_app/t/$id': typeof AppTIdRoute
  '/_app/types/$id': typeof AppTypesIdRoute
  '/_app/vendors/$id': typeof AppVendorsIdRoute
  '/_print/labels/$batchId': typeof PrintLabelsBatchIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/assistant/': typeof AppAssistantIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/admin/ai/usage': typeof AppAdminAiUsageRoute
  '/_app/settings/account/brands': typeof AppSettingsAccountBrandsRoute
  '/_app/settings/account/exchange-rates': typeof AppSettingsAccountExchangeRatesRoute
  '/_app/settings/account/people': typeof AppSettingsAccountPeopleRoute
  '/_app/settings/account/place-kinds': typeof AppSettingsAccountPlaceKindsRoute
  '/_app/settings/account/tags': typeof AppSettingsAccountTagsRoute
  '/_app/settings/account/templates': typeof AppSettingsAccountTemplatesRoute
  '/_app/settings/account/types': typeof AppSettingsAccountTypesRoute
  '/_app/settings/account/vendors': typeof AppSettingsAccountVendorsRoute
  '/_app/settings/ai/usage': typeof AppSettingsAiUsageRoute
  '/_app/settings/me/ai': typeof AppSettingsMeAiRoute
  '/_app/settings/me/notifications': typeof AppSettingsMeNotificationsRoute
  '/_app/settings/account/': typeof AppSettingsAccountIndexRoute
  '/_app/settings/location/$id/general': typeof AppSettingsLocationIdGeneralRoute
  '/_app/settings/location/$id/invite': typeof AppSettingsLocationIdInviteRoute
  '/_app/settings/location/$id/members': typeof AppSettingsLocationIdMembersRoute
  '/_app/settings/location/$id/track': typeof AppSettingsLocationIdTrackRoute
  '/_app/settings/location/$id/webhooks': typeof AppSettingsLocationIdWebhooksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/invite'
    | '/setup'
    | '/activity'
    | '/admin'
    | '/capture'
    | '/consumables'
    | '/expiring'
    | '/help'
    | '/inbox'
    | '/incidents'
    | '/labels'
    | '/lending'
    | '/more'
    | '/notifications'
    | '/paperwork'
    | '/scan'
    | '/schedules'
    | '/search'
    | '/trash'
    | '/vehicles'
    | '/auth/confirm'
    | '/auth/email-change'
    | '/auth/reset'
    | '/oauth/consent'
    | '/signin/code'
    | '/signin/two-factor'
    | '/signin/'
    | '/a/$assetId'
    | '/admin/admins'
    | '/admin/ai'
    | '/admin/alerts'
    | '/admin/backups'
    | '/admin/currencies'
    | '/admin/jobs'
    | '/admin/settings'
    | '/admin/status'
    | '/admin/users'
    | '/assistant/$threadId'
    | '/box-check/$id'
    | '/brands/$id'
    | '/incidents/$id'
    | '/item/$uuid'
    | '/l/$code'
    | '/loc/$id'
    | '/location/$uuid'
    | '/locations/new'
    | '/p/$id'
    | '/people/$id'
    | '/reports/$kind'
    | '/settings/account'
    | '/settings/ai'
    | '/settings/connections'
    | '/settings/device'
    | '/settings/diagnostics'
    | '/settings/export'
    | '/settings/import'
    | '/settings/locations'
    | '/settings/two-factor'
    | '/t/$id'
    | '/types/$id'
    | '/vendors/$id'
    | '/labels/$batchId'
    | '/admin/'
    | '/assistant/'
    | '/settings/'
    | '/admin/ai/usage'
    | '/settings/account/brands'
    | '/settings/account/exchange-rates'
    | '/settings/account/people'
    | '/settings/account/place-kinds'
    | '/settings/account/tags'
    | '/settings/account/templates'
    | '/settings/account/types'
    | '/settings/account/vendors'
    | '/settings/ai/usage'
    | '/settings/me/ai'
    | '/settings/me/notifications'
    | '/settings/account/'
    | '/settings/location/$id/general'
    | '/settings/location/$id/invite'
    | '/settings/location/$id/members'
    | '/settings/location/$id/track'
    | '/settings/location/$id/webhooks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/invite'
    | '/setup'
    | '/activity'
    | '/capture'
    | '/consumables'
    | '/expiring'
    | '/help'
    | '/inbox'
    | '/incidents'
    | '/labels'
    | '/lending'
    | '/more'
    | '/notifications'
    | '/paperwork'
    | '/scan'
    | '/schedules'
    | '/search'
    | '/trash'
    | '/vehicles'
    | '/auth/confirm'
    | '/auth/email-change'
    | '/auth/reset'
    | '/oauth/consent'
    | '/signin/code'
    | '/signin/two-factor'
    | '/signin'
    | '/a/$assetId'
    | '/admin/admins'
    | '/admin/ai'
    | '/admin/alerts'
    | '/admin/backups'
    | '/admin/currencies'
    | '/admin/jobs'
    | '/admin/settings'
    | '/admin/status'
    | '/admin/users'
    | '/assistant/$threadId'
    | '/box-check/$id'
    | '/brands/$id'
    | '/incidents/$id'
    | '/item/$uuid'
    | '/l/$code'
    | '/loc/$id'
    | '/location/$uuid'
    | '/locations/new'
    | '/p/$id'
    | '/people/$id'
    | '/reports/$kind'
    | '/settings/ai'
    | '/settings/connections'
    | '/settings/device'
    | '/settings/diagnostics'
    | '/settings/export'
    | '/settings/import'
    | '/settings/locations'
    | '/settings/two-factor'
    | '/t/$id'
    | '/types/$id'
    | '/vendors/$id'
    | '/labels/$batchId'
    | '/admin'
    | '/assistant'
    | '/settings'
    | '/admin/ai/usage'
    | '/settings/account/brands'
    | '/settings/account/exchange-rates'
    | '/settings/account/people'
    | '/settings/account/place-kinds'
    | '/settings/account/tags'
    | '/settings/account/templates'
    | '/settings/account/types'
    | '/settings/account/vendors'
    | '/settings/ai/usage'
    | '/settings/me/ai'
    | '/settings/me/notifications'
    | '/settings/account'
    | '/settings/location/$id/general'
    | '/settings/location/$id/invite'
    | '/settings/location/$id/members'
    | '/settings/location/$id/track'
    | '/settings/location/$id/webhooks'
  id:
    | '__root__'
    | '/_app'
    | '/_print'
    | '/gallery'
    | '/invite'
    | '/setup'
    | '/_app/activity'
    | '/_app/admin'
    | '/_app/capture'
    | '/_app/consumables'
    | '/_app/expiring'
    | '/_app/help'
    | '/_app/inbox'
    | '/_app/incidents'
    | '/_app/labels'
    | '/_app/lending'
    | '/_app/more'
    | '/_app/notifications'
    | '/_app/paperwork'
    | '/_app/scan'
    | '/_app/schedules'
    | '/_app/search'
    | '/_app/trash'
    | '/_app/vehicles'
    | '/auth/confirm'
    | '/auth/email-change'
    | '/auth/reset'
    | '/oauth/consent'
    | '/signin/code'
    | '/signin/two-factor'
    | '/_app/'
    | '/signin/'
    | '/_app/a/$assetId'
    | '/_app/admin/admins'
    | '/_app/admin/ai'
    | '/_app/admin/alerts'
    | '/_app/admin/backups'
    | '/_app/admin/currencies'
    | '/_app/admin/jobs'
    | '/_app/admin/settings'
    | '/_app/admin/status'
    | '/_app/admin/users'
    | '/_app/assistant/$threadId'
    | '/_app/box-check/$id'
    | '/_app/brands/$id'
    | '/_app/incidents/$id'
    | '/_app/item/$uuid'
    | '/_app/l/$code'
    | '/_app/loc/$id'
    | '/_app/location/$uuid'
    | '/_app/locations/new'
    | '/_app/p/$id'
    | '/_app/people/$id'
    | '/_app/reports/$kind'
    | '/_app/settings/account'
    | '/_app/settings/ai'
    | '/_app/settings/connections'
    | '/_app/settings/device'
    | '/_app/settings/diagnostics'
    | '/_app/settings/export'
    | '/_app/settings/import'
    | '/_app/settings/locations'
    | '/_app/settings/two-factor'
    | '/_app/t/$id'
    | '/_app/types/$id'
    | '/_app/vendors/$id'
    | '/_print/labels/$batchId'
    | '/_app/admin/'
    | '/_app/assistant/'
    | '/_app/settings/'
    | '/_app/admin/ai/usage'
    | '/_app/settings/account/brands'
    | '/_app/settings/account/exchange-rates'
    | '/_app/settings/account/people'
    | '/_app/settings/account/place-kinds'
    | '/_app/settings/account/tags'
    | '/_app/settings/account/templates'
    | '/_app/settings/account/types'
    | '/_app/settings/account/vendors'
    | '/_app/settings/ai/usage'
    | '/_app/settings/me/ai'
    | '/_app/settings/me/notifications'
    | '/_app/settings/account/'
    | '/_app/settings/location/$id/general'
    | '/_app/settings/location/$id/invite'
    | '/_app/settings/location/$id/members'
    | '/_app/settings/location/$id/track'
    | '/_app/settings/location/$id/webhooks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PrintRoute: typeof PrintRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  InviteRoute: typeof InviteRoute
  SetupRoute: typeof SetupRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthEmailChangeRoute: typeof AuthEmailChangeRoute
  AuthResetRoute: typeof AuthResetRoute
  OauthConsentRoute: typeof OauthConsentRoute
  SigninCodeRoute: typeof SigninCodeRoute
  SigninTwoFactorRoute: typeof SigninTwoFactorRoute
  SigninIndexRoute: typeof SigninIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_print': {
      id: '/_print'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/capture': {
      id: '/_app/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof AppCaptureRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consumables': {
      id: '/_app/consumables'
      path: '/consumables'
      fullPath: '/consumables'
      preLoaderRoute: typeof AppConsumablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expiring': {
      id: '/_app/expiring'
      path: '/expiring'
      fullPath: '/expiring'
      preLoaderRoute: typeof AppExpiringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents': {
      id: '/_app/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labels': {
      id: '/_app/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof AppLabelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lending': {
      id: '/_app/lending'
      path: '/lending'
      fullPath: '/lending'
      preLoaderRoute: typeof AppLendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/paperwork': {
      id: '/_app/paperwork'
      path: '/paperwork'
      fullPath: '/paperwork'
      preLoaderRoute: typeof AppPaperworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedules': {
      id: '/_app/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AppSchedulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trash': {
      id: '/_app/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AppTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vehicles': {
      id: '/_app/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AppVehiclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/email-change': {
      id: '/auth/email-change'
      path: '/auth/email-change'
      fullPath: '/auth/email-change'
      preLoaderRoute: typeof AuthEmailChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof SigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/code': {
      id: '/signin/code'
      path: '/signin/code'
      fullPath: '/signin/code'
      preLoaderRoute: typeof SigninCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/two-factor': {
      id: '/signin/two-factor'
      path: '/signin/two-factor'
      fullPath: '/signin/two-factor'
      preLoaderRoute: typeof SigninTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/a/$assetId': {
      id: '/_app/a/$assetId'
      path: '/a/$assetId'
      fullPath: '/a/$assetId'
      preLoaderRoute: typeof AppAAssetIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/admins': {
      id: '/_app/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AppAdminAdminsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/ai': {
      id: '/_app/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AppAdminAiRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/alerts': {
      id: '/_app/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AppAdminAlertsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/backups': {
      id: '/_app/admin/backups'
      path: '/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AppAdminBackupsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/currencies': {
      id: '/_app/admin/currencies'
      path: '/currencies'
      fullPath: '/admin/currencies'
      preLoaderRoute: typeof AppAdminCurrenciesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/jobs': {
      id: '/_app/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AppAdminJobsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/status': {
      id: '/_app/admin/status'
      path: '/status'
      fullPath: '/admin/status'
      preLoaderRoute: typeof AppAdminStatusRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/assistant/': {
      id: '/_app/assistant/'
      path: '/assistant'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AppAssistantIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant/$threadId': {
      id: '/_app/assistant/$threadId'
      path: '/assistant/$threadId'
      fullPath: '/assistant/$threadId'
      preLoaderRoute: typeof AppAssistantThreadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/box-check/$id': {
      id: '/_app/box-check/$id'
      path: '/box-check/$id'
      fullPath: '/box-check/$id'
      preLoaderRoute: typeof AppBoxCheckIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/$id': {
      id: '/_app/brands/$id'
      path: '/brands/$id'
      fullPath: '/brands/$id'
      preLoaderRoute: typeof AppBrandsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents/$id': {
      id: '/_app/incidents/$id'
      path: '/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof AppIncidentsIdRouteImport
      parentRoute: typeof AppIncidentsRoute
    }
    '/_app/item/$uuid': {
      id: '/_app/item/$uuid'
      path: '/item/$uuid'
      fullPath: '/item/$uuid'
      preLoaderRoute: typeof AppItemUuidRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/l/$code': {
      id: '/_app/l/$code'
      path: '/l/$code'
      fullPath: '/l/$code'
      preLoaderRoute: typeof AppLCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loc/$id': {
      id: '/_app/loc/$id'
      path: '/loc/$id'
      fullPath: '/loc/$id'
      preLoaderRoute: typeof AppLocIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/location/$uuid': {
      id: '/_app/location/$uuid'
      path: '/location/$uuid'
      fullPath: '/location/$uuid'
      preLoaderRoute: typeof AppLocationUuidRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locations/new': {
      id: '/_app/locations/new'
      path: '/locations/new'
      fullPath: '/locations/new'
      preLoaderRoute: typeof AppLocationsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/p/$id': {
      id: '/_app/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof AppPIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/$id': {
      id: '/_app/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof AppPeopleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/$kind': {
      id: '/_app/reports/$kind'
      path: '/reports/$kind'
      fullPath: '/reports/$kind'
      preLoaderRoute: typeof AppReportsKindRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/ai': {
      id: '/_app/settings/ai'
      path: '/settings/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AppSettingsAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/connections': {
      id: '/_app/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof AppSettingsConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/device': {
      id: '/_app/settings/device'
      path: '/settings/device'
      fullPath: '/settings/device'
      preLoaderRoute: typeof AppSettingsDeviceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/diagnostics': {
      id: '/_app/settings/diagnostics'
      path: '/settings/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof AppSettingsDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/export': {
      id: '/_app/settings/export'
      path: '/settings/export'
      fullPath: '/settings/export'
      preLoaderRoute: typeof AppSettingsExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/import': {
      id: '/_app/settings/import'
      path: '/settings/import'
      fullPath: '/settings/import'
      preLoaderRoute: typeof AppSettingsImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/locations': {
      id: '/_app/settings/locations'
      path: '/settings/locations'
      fullPath: '/settings/locations'
      preLoaderRoute: typeof AppSettingsLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/two-factor': {
      id: '/_app/settings/two-factor'
      path: '/settings/two-factor'
      fullPath: '/settings/two-factor'
      preLoaderRoute: typeof AppSettingsTwoFactorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/t/$id': {
      id: '/_app/t/$id'
      path: '/t/$id'
      fullPath: '/t/$id'
      preLoaderRoute: typeof AppTIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/types/$id': {
      id: '/_app/types/$id'
      path: '/types/$id'
      fullPath: '/types/$id'
      preLoaderRoute: typeof AppTypesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors/$id': {
      id: '/_app/vendors/$id'
      path: '/vendors/$id'
      fullPath: '/vendors/$id'
      preLoaderRoute: typeof AppVendorsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_print/labels/$batchId': {
      id: '/_print/labels/$batchId'
      path: '/labels/$batchId'
      fullPath: '/labels/$batchId'
      preLoaderRoute: typeof PrintLabelsBatchIdRouteImport
      parentRoute: typeof PrintRoute
    }
    '/_app/admin/ai/usage': {
      id: '/_app/admin/ai/usage'
      path: '/usage'
      fullPath: '/admin/ai/usage'
      preLoaderRoute: typeof AppAdminAiUsageRouteImport
      parentRoute: typeof AppAdminAiRoute
    }
    '/_app/settings/account/': {
      id: '/_app/settings/account/'
      path: '/'
      fullPath: '/settings/account/'
      preLoaderRoute: typeof AppSettingsAccountIndexRouteImport
      parentRoute: typeof AppSettingsAccountRoute
    }
    '/_app/settings/account/brands': {
      id: '/_app/settings/account/brands'
      path: '/brands'
      fullPath: '/settings/account/brands'
      preLoaderRoute: typeof AppSettingsAccountBrandsRouteImport
      parentRoute: typeof AppSettingsAccountRoute
    }
    '/_app/settings/account/exchange-rates': {
      id: '/_app/settings/account/exchange-rates'
      path: '/exchange-rates'
      fullPath: '/settings/account/exchange-rates'
      preLoaderRoute: typeof AppSettingsAccountExchangeRatesRouteImport
      parentRoute: typeof AppSettingsAccountRoute
    }
    '/_app/settings/account/people': {
      id: '/_app/settings/account/people'
      path: '/people'
      fullPath: '/settings/account/people'
      preLoaderRoute: typeof AppSettingsAccountPeopleRouteImport
      parentRoute: typeof AppSettingsAccountRoute
    }
    '/_app/settings/account/place-kinds': {
      id: '/_app/settings/account/place-kinds'
      path: '/place-kinds'
      fullPath: '/settings/account/place-kinds'
      preLoaderRoute: typeof AppSettingsAccountPlaceKindsRouteImport
      parentRoute: typeof AppSettingsAccountRoute
    }
    '/_app/settings/account/tags': {
      id: '/_app/settings/account/tags'
      path: '/tags'
      fullPath: '/settings/account/tags'
      preLoaderRoute: typeof AppSettingsAccountTagsRouteImport
      parentRoute: typeof AppSettingsAccountRoute
    }
    '/_app/settings/account/templates': {
      id: '/_app/settings/account/templates'
      path: '/templates'
      fullPath: '/settings/account/templates'
      preLoaderRoute: typeof AppSettingsAccountTemplatesRouteImport
      parentRoute: typeof AppSettingsAccountRoute
    }
    '/_app/settings/account/types': {
      id: '/_app/settings/account/types'
      path: '/types'
      fullPath: '/settings/account/types'
      preLoaderRoute: typeof AppSettingsAccountTypesRouteImport
      parentRoute: typeof AppSettingsAccountRoute
    }
    '/_app/settings/account/vendors': {
      id: '/_app/settings/account/vendors'
      path: '/vendors'
      fullPath: '/settings/account/vendors'
      preLoaderRoute: typeof AppSettingsAccountVendorsRouteImport
      parentRoute: typeof AppSettingsAccountRoute
    }
    '/_app/settings/ai/usage': {
      id: '/_app/settings/ai/usage'
      path: '/usage'
      fullPath: '/settings/ai/usage'
      preLoaderRoute: typeof AppSettingsAiUsageRouteImport
      parentRoute: typeof AppSettingsAiRoute
    }
    '/_app/settings/me/ai': {
      id: '/_app/settings/me/ai'
      path: '/settings/me/ai'
      fullPath: '/settings/me/ai'
      preLoaderRoute: typeof AppSettingsMeAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/me/notifications': {
      id: '/_app/settings/me/notifications'
      path: '/settings/me/notifications'
      fullPath: '/settings/me/notifications'
      preLoaderRoute: typeof AppSettingsMeNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/location/$id/general': {
      id: '/_app/settings/location/$id/general'
      path: '/settings/location/$id/general'
      fullPath: '/settings/location/$id/general'
      preLoaderRoute: typeof AppSettingsLocationIdGeneralRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/location/$id/invite': {
      id: '/_app/settings/location/$id/invite'
      path: '/settings/location/$id/invite'
      fullPath: '/settings/location/$id/invite'
      preLoaderRoute: typeof AppSettingsLocationIdInviteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/location/$id/members': {
      id: '/_app/settings/location/$id/members'
      path: '/settings/location/$id/members'
      fullPath: '/settings/location/$id/members'
      preLoaderRoute: typeof AppSettingsLocationIdMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/location/$id/track': {
      id: '/_app/settings/location/$id/track'
      path: '/settings/location/$id/track'
      fullPath: '/settings/location/$id/track'
      preLoaderRoute: typeof AppSettingsLocationIdTrackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/location/$id/webhooks': {
      id: '/_app/settings/location/$id/webhooks'
      path: '/settings/location/$id/webhooks'
      fullPath: '/settings/location/$id/webhooks'
      preLoaderRoute: typeof AppSettingsLocationIdWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAdminAiRouteChildren {
  AppAdminAiUsageRoute: typeof AppAdminAiUsageRoute
}

const AppAdminAiRouteChildren: AppAdminAiRouteChildren = {
  AppAdminAiUsageRoute: AppAdminAiUsageRoute,
}

const AppAdminAiRouteWithChildren = AppAdminAiRoute._addFileChildren(
  AppAdminAiRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminAdminsRoute: typeof AppAdminAdminsRoute
  AppAdminAiRoute: typeof AppAdminAiRouteWithChildren
  AppAdminAlertsRoute: typeof AppAdminAlertsRoute
  AppAdminBackupsRoute: typeof AppAdminBackupsRoute
  AppAdminCurrenciesRoute: typeof AppAdminCurrenciesRoute
  AppAdminJobsRoute: typeof AppAdminJobsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminStatusRoute: typeof AppAdminStatusRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAdminsRoute: AppAdminAdminsRoute,
  AppAdminAiRoute: AppAdminAiRouteWithChildren,
  AppAdminAlertsRoute: AppAdminAlertsRoute,
  AppAdminBackupsRoute: AppAdminBackupsRoute,
  AppAdminCurrenciesRoute: AppAdminCurrenciesRoute,
  AppAdminJobsRoute: AppAdminJobsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminStatusRoute: AppAdminStatusRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppIncidentsRouteChildren {
  AppIncidentsIdRoute: typeof AppIncidentsIdRoute
}

const AppIncidentsRouteChildren: AppIncidentsRouteChildren = {
  AppIncidentsIdRoute: AppIncidentsIdRoute,
}

const AppIncidentsRouteWithChildren = AppIncidentsRoute._addFileChildren(
  AppIncidentsRouteChildren,
)

interface AppSettingsAccountRouteChildren {
  AppSettingsAccountBrandsRoute: typeof AppSettingsAccountBrandsRoute
  AppSettingsAccountExchangeRatesRoute: typeof AppSettingsAccountExchangeRatesRoute
  AppSettingsAccountPeopleRoute: typeof AppSettingsAccountPeopleRoute
  AppSettingsAccountPlaceKindsRoute: typeof AppSettingsAccountPlaceKindsRoute
  AppSettingsAccountTagsRoute: typeof AppSettingsAccountTagsRoute
  AppSettingsAccountTemplatesRoute: typeof AppSettingsAccountTemplatesRoute
  AppSettingsAccountTypesRoute: typeof AppSettingsAccountTypesRoute
  AppSettingsAccountVendorsRoute: typeof AppSettingsAccountVendorsRoute
  AppSettingsAccountIndexRoute: typeof AppSettingsAccountIndexRoute
}

const AppSettingsAccountRouteChildren: AppSettingsAccountRouteChildren = {
  AppSettingsAccountBrandsRoute: AppSettingsAccountBrandsRoute,
  AppSettingsAccountExchangeRatesRoute: AppSettingsAccountExchangeRatesRoute,
  AppSettingsAccountPeopleRoute: AppSettingsAccountPeopleRoute,
  AppSettingsAccountPlaceKindsRoute: AppSettingsAccountPlaceKindsRoute,
  AppSettingsAccountTagsRoute: AppSettingsAccountTagsRoute,
  AppSettingsAccountTemplatesRoute: AppSettingsAccountTemplatesRoute,
  AppSettingsAccountTypesRoute: AppSettingsAccountTypesRoute,
  AppSettingsAccountVendorsRoute: AppSettingsAccountVendorsRoute,
  AppSettingsAccountIndexRoute: AppSettingsAccountIndexRoute,
}

const AppSettingsAccountRouteWithChildren =
  AppSettingsAccountRoute._addFileChildren(AppSettingsAccountRouteChildren)

interface AppSettingsAiRouteChildren {
  AppSettingsAiUsageRoute: typeof AppSettingsAiUsageRoute
}

const AppSettingsAiRouteChildren: AppSettingsAiRouteChildren = {
  AppSettingsAiUsageRoute: AppSettingsAiUsageRoute,
}

const AppSettingsAiRouteWithChildren = AppSettingsAiRoute._addFileChildren(
  AppSettingsAiRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppCaptureRoute: typeof AppCaptureRoute
  AppConsumablesRoute: typeof AppConsumablesRoute
  AppExpiringRoute: typeof AppExpiringRoute
  AppHelpRoute: typeof AppHelpRoute
  AppInboxRoute: typeof AppInboxRoute
  AppIncidentsRoute: typeof AppIncidentsRouteWithChildren
  AppLabelsRoute: typeof AppLabelsRoute
  AppLendingRoute: typeof AppLendingRoute
  AppMoreRoute: typeof AppMoreRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPaperworkRoute: typeof AppPaperworkRoute
  AppScanRoute: typeof AppScanRoute
  AppSchedulesRoute: typeof AppSchedulesRoute
  AppSearchRoute: typeof AppSearchRoute
  AppTrashRoute: typeof AppTrashRoute
  AppVehiclesRoute: typeof AppVehiclesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAAssetIdRoute: typeof AppAAssetIdRoute
  AppAssistantThreadIdRoute: typeof AppAssistantThreadIdRoute
  AppBoxCheckIdRoute: typeof AppBoxCheckIdRoute
  AppBrandsIdRoute: typeof AppBrandsIdRoute
  AppItemUuidRoute: typeof AppItemUuidRoute
  AppLCodeRoute: typeof AppLCodeRoute
  AppLocIdRoute: typeof AppLocIdRoute
  AppLocationUuidRoute: typeof AppLocationUuidRoute
  AppLocationsNewRoute: typeof AppLocationsNewRoute
  AppPIdRoute: typeof AppPIdRoute
  AppPeopleIdRoute: typeof AppPeopleIdRoute
  AppReportsKindRoute: typeof AppReportsKindRoute
  AppSettingsAccountRoute: typeof AppSettingsAccountRouteWithChildren
  AppSettingsAiRoute: typeof AppSettingsAiRouteWithChildren
  AppSettingsConnectionsRoute: typeof AppSettingsConnectionsRoute
  AppSettingsDeviceRoute: typeof AppSettingsDeviceRoute
  AppSettingsDiagnosticsRoute: typeof AppSettingsDiagnosticsRoute
  AppSettingsExportRoute: typeof AppSettingsExportRoute
  AppSettingsImportRoute: typeof AppSettingsImportRoute
  AppSettingsLocationsRoute: typeof AppSettingsLocationsRoute
  AppSettingsTwoFactorRoute: typeof AppSettingsTwoFactorRoute
  AppTIdRoute: typeof AppTIdRoute
  AppTypesIdRoute: typeof AppTypesIdRoute
  AppVendorsIdRoute: typeof AppVendorsIdRoute
  AppAssistantIndexRoute: typeof AppAssistantIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSettingsMeAiRoute: typeof AppSettingsMeAiRoute
  AppSettingsMeNotificationsRoute: typeof AppSettingsMeNotificationsRoute
  AppSettingsLocationIdGeneralRoute: typeof AppSettingsLocationIdGeneralRoute
  AppSettingsLocationIdInviteRoute: typeof AppSettingsLocationIdInviteRoute
  AppSettingsLocationIdMembersRoute: typeof AppSettingsLocationIdMembersRoute
  AppSettingsLocationIdTrackRoute: typeof AppSettingsLocationIdTrackRoute
  AppSettingsLocationIdWebhooksRoute: typeof AppSettingsLocationIdWebhooksRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCaptureRoute: AppCaptureRoute,
  AppConsumablesRoute: AppConsumablesRoute,
  AppExpiringRoute: AppExpiringRoute,
  AppHelpRoute: AppHelpRoute,
  AppInboxRoute: AppInboxRoute,
  AppIncidentsRoute: AppIncidentsRouteWithChildren,
  AppLabelsRoute: AppLabelsRoute,
  AppLendingRoute: AppLendingRoute,
  AppMoreRoute: AppMoreRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPaperworkRoute: AppPaperworkRoute,
  AppScanRoute: AppScanRoute,
  AppSchedulesRoute: AppSchedulesRoute,
  AppSearchRoute: AppSearchRoute,
  AppTrashRoute: AppTrashRoute,
  AppVehiclesRoute: AppVehiclesRoute,
  AppIndexRoute: AppIndexRoute,
  AppAAssetIdRoute: AppAAssetIdRoute,
  AppAssistantThreadIdRoute: AppAssistantThreadIdRoute,
  AppBoxCheckIdRoute: AppBoxCheckIdRoute,
  AppBrandsIdRoute: AppBrandsIdRoute,
  AppItemUuidRoute: AppItemUuidRoute,
  AppLCodeRoute: AppLCodeRoute,
  AppLocIdRoute: AppLocIdRoute,
  AppLocationUuidRoute: AppLocationUuidRoute,
  AppLocationsNewRoute: AppLocationsNewRoute,
  AppPIdRoute: AppPIdRoute,
  AppPeopleIdRoute: AppPeopleIdRoute,
  AppReportsKindRoute: AppReportsKindRoute,
  AppSettingsAccountRoute: AppSettingsAccountRouteWithChildren,
  AppSettingsAiRoute: AppSettingsAiRouteWithChildren,
  AppSettingsConnectionsRoute: AppSettingsConnectionsRoute,
  AppSettingsDeviceRoute: AppSettingsDeviceRoute,
  AppSettingsDiagnosticsRoute: AppSettingsDiagnosticsRoute,
  AppSettingsExportRoute: AppSettingsExportRoute,
  AppSettingsImportRoute: AppSettingsImportRoute,
  AppSettingsLocationsRoute: AppSettingsLocationsRoute,
  AppSettingsTwoFactorRoute: AppSettingsTwoFactorRoute,
  AppTIdRoute: AppTIdRoute,
  AppTypesIdRoute: AppTypesIdRoute,
  AppVendorsIdRoute: AppVendorsIdRoute,
  AppAssistantIndexRoute: AppAssistantIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSettingsMeAiRoute: AppSettingsMeAiRoute,
  AppSettingsMeNotificationsRoute: AppSettingsMeNotificationsRoute,
  AppSettingsLocationIdGeneralRoute: AppSettingsLocationIdGeneralRoute,
  AppSettingsLocationIdInviteRoute: AppSettingsLocationIdInviteRoute,
  AppSettingsLocationIdMembersRoute: AppSettingsLocationIdMembersRoute,
  AppSettingsLocationIdTrackRoute: AppSettingsLocationIdTrackRoute,
  AppSettingsLocationIdWebhooksRoute: AppSettingsLocationIdWebhooksRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PrintRouteChildren {
  PrintLabelsBatchIdRoute: typeof PrintLabelsBatchIdRoute
}

const PrintRouteChildren: PrintRouteChildren = {
  PrintLabelsBatchIdRoute: PrintLabelsBatchIdRoute,
}

const PrintRouteWithChildren = PrintRoute._addFileChildren(PrintRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PrintRoute: PrintRouteWithChildren,
  GalleryRoute: GalleryRoute,
  InviteRoute: InviteRoute,
  SetupRoute: SetupRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthEmailChangeRoute: AuthEmailChangeRoute,
  AuthResetRoute: AuthResetRoute,
  OauthConsentRoute: OauthConsentRoute,
  SigninCodeRoute: SigninCodeRoute,
  SigninTwoFactorRoute: SigninTwoFactorRoute,
  SigninIndexRoute: SigninIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
