// The configuration reference page (D81, D187 "a configuration reference per version"), rendered
// from the server's env schema (apps/server/src/config/env.ts) through the same function as
// `kept admin config`. The page is committed; `--check` fails when it differs from what the code
// renders now, so the docs can't drift from the variables Kept reads.
//
//   pnpm --filter @kept/docs gen:config      rewrite the page
//   pnpm --filter @kept/docs check:config    exit 1 if it is stale (ci-local's `docs` step)
import { readFileSync, writeFileSync } from 'node:fs';
import { renderEnvReference } from '../../server/src/config/reference.js';

const args = process.argv.slice(2);
const check = args.includes('--check');
const out = args.find((a) => !a.startsWith('--'));
if (!out) throw new Error('usage: env-reference.ts [--check] <page.md>');

/** Markdown would read `<name>` outside a code span as an HTML tag: escape it there only. */
export function escapeOutsideCode(cell: string): string {
  return cell
    .split(/(`[^`]*`)/)
    .map((part) =>
      part.startsWith('`') ? part : part.replaceAll('<', '&lt;').replaceAll('>', '&gt;'),
    )
    .join('');
}

export function renderPage(table: string): string {
  const rows = table.split('\n').map(escapeOutsideCode).join('\n');
  return `---
title: Configuration reference
description: Every environment variable Kept reads, its default and what it does.
sidebar:
  order: 1
---

<!-- Generated by apps/docs/scripts/env-reference.ts from apps/server/src/config/env.ts. Do not edit: run \`pnpm --filter @kept/docs gen:config\`. -->

Kept is configured with environment variables. **An environment variable always beats the same
setting in the admin screens**, which then shows it as locked. \`kept admin config\` prints this
same table from the server you are running, so it always matches your version.

The Compose file passes the common ones through from \`.env\`; the rest go in a
\`compose.override.yaml\` next to it.

${rows}
`;
}

const page = renderPage(renderEnvReference());
if (check) {
  let current = '';
  try {
    current = readFileSync(out, 'utf8');
  } catch {}
  if (current !== page) {
    console.error(
      `${out} is stale: the env schema changed. Run \`pnpm --filter @kept/docs gen:config\` and commit it.`,
    );
    process.exit(1);
  }
  console.log(`${out} matches the env schema`);
} else {
  writeFileSync(out, page);
  console.log(`wrote ${out}`);
}
