apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kept
spec:
  selector: {app.kubernetes.io/name: kept, app.kubernetes.io/instance: {{ .Release.Name }}}
  ports: [{name: http, port: 80, targetPort: http}]
