apiVersion: v1
kind: Service
metadata:
  name: {{ include "kept.fullname" . }}
  labels:
    {{- include "kept.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "kept.selector" (dict "root" . "component" (include "kept.webComponent" .)) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
